### ISSUE TITLE
[features] Disable untracked file shown in diff

### ISSUE THREAD

**Issue by ray-x** [sindrets/diffview.nvim#10]
would be good to provide a option to exclude untracked files

**Comment by sindrets** [comment]
As of #5 Diffview respects your git config on the matter. So if you set

```sh
git config status.showUntrackedFiles false
```

Untracked files won't show up in the Diffview. But I agree, we should be able to pass a flag to `:DiffviewOpen` for one-shot enable/disable of untracked files.

**Comment by bew** [comment]
Hmm instead of using `ls-files` to find untracked files, I'd like to suggest using `git status --porcelain`, which gives an output like this:
```
 M a-modified-file
 A a-new-file
 M nvim/another-modified-file
?? this-is-an-untracked-file
```
The lines starting with `??` are the untracked files, so you can decide whether to have them or not based on a config on your side!

**Comment by sindrets** [comment]
@bew It's already based on the config on your side. Like I explained, I check for `status.showUntrackedFiles`. `git status` doesn't support rev's, so I can't use that to find modified files, and it would just be extra parsing to use it for untracked files as I would have to filter out the things I don't need.
Anyway, I'm almost done implementing an arg option that you can optionally pass to `:DiffviewOpen`, and that will override your local config.

**Comment by bew** [comment]
Okay, I'm trying to understand though, you don't need revs for status, because untracked files are never in git by definition, why would you need the rev for?

**Comment by sindrets** [comment]
Sorry for the confusion. I thought you were suggesting that I use a single `git status` command for find both modified and untracked files, instead of what I'm doing now, which is using `git diff --name-status {REV}` to find modified files, and `git ls-files` for untracked when it's needed.

**Comment by bew** [comment]
Ah yes no, I wasn't trying to suggest that indeed, but to use `git status ...` only to find untracked files, to replace `ls-files` (I'm guessing you're using it only to find untracked files?)

**Comment by sindrets** [comment]
@bew just to be clear: you're suggesting changing `git ls-files ...` to `git status ...` to avoid checking the value for `status.showUntrackedFiles` manually? It would reduce overhead a little bit by avoiding the extra system call. If you put up a PR, I'll merge.

**Comment by sindrets** [comment]
@ray-x You can now hide untracked files regardless of your local git config by providing an additional arg to `:DiffviewOpen`:

```vimhelp
:DiffviewOpen [git-rev] [args] [ -- {paths...}]
    ...
    Args:
        -u[value], --untracked-files[={value}]
                        Specify whether or not to show untracked files. If
                        flag is given without value; defaults to `true`.
                        {value} can be one of:
                          - `true`, `normal`, `all` Show untracked.
                          - `false`, `no` Don't show untracked.
```

Example usage:

```
:DiffviewOpen HEAD~2 -uno
:DiffviewOpen HEAD~2 --untracked-files=all
```

**Comment by ray-x** [comment]
Great, thanks!
