### ISSUE TITLE
[feature request] Follow symlink to src file

### ISSUE THREAD

**Issue by lsternlicht** [sindrets/diffview.nvim#104]
It would be great if the plugin could identify the **source file** if a symlink is currently loaded in the buffer to identify the **parent git repository**.

For example, I have file the following file:
```bash
ls -la | grep profile
lrwxr-xr-x    1 <username>  staff         50 Nov 30 11:57 .profile -> /Users/<username>/.dotfiles/profile
```
If I run `:DiffviewOpen` I get the following error:
`[Diffview.nvim] Path not a git repo (or any parent): '/Users/<username>'`

**Comment by sindrets** [comment]
Good idea! Implemented in the latest commit.
