### ISSUE TITLE
[Question] Is it possible to compare two files/folders?

### ISSUE THREAD

**Issue by ray-x** [sindrets/diffview.nvim#105]
From readme, it can only compare through git version. Is it possible to compare two files/folders?

**Comment by sindrets** [comment]
@ray-x comparing two files is supported natively in vim. Just open the first file, then `:diffsplit other/file`. See `:h diffsplit` for more info.

Comparing any two folders is not currently supported. Is this a feature you would like to see implemented?

**Comment by ray-x** [comment]
Thanks for the suggestions. 
Would be great to select & compare files/folders from Diffview.
My preferred workflow is `Diffview folder1 folder1` and diffview will show split view of two folders and I can select two files from the diffview pannel.

**Comment by tzws** [comment]
@ray-x  the same workflow for me. Beyond compare is my second most used tool. Compare folder is much more efficient than CVS system when you want to go through a lot of changes.

**Comment by sindrets** [comment]
> Compare folder is much more efficient than CVS system when you want to go through a lot of changes.

@tzws I disagree. If your project is already tracked in git, it gives you a lot more flexibility. Being able to diff between any two revisions, across branches and work trees is far more powerful than diffing two folders on disk.

This is a very git-centered plugin, but I am willing to add non-git functionality as well.

> My preferred workflow is `Diffview folder1 folder1` and diffview will show split view of two folders and I can select two files from the diffview pannel.

@ray-x I don't really see the point of implementing a porcelain interface around this workflow in this plugin, as this seems to be well covered by commands and functionality that already exists in vim. The way you would do this, without any plugins:

- Open a new tab page
- Make a new split for the diff.
- `:1windo lcd folder1 | 2windo lcd folder2`
  - If you use a fuzzy finder for finding files; this should make it easy to find files in your two given folders (as long as your fuzzy finder of choice respects the local cwd. I know Telescope does, I assume fzf.vim does as well.)
- Open a file in both of the windows and enable diff mode with: `:windo diffthis`

You could easily create a small custom command that automates this behavior. Something like:

```vim
" The last line in the command opens the local cwd for each window if you have
" a netrw-like explorer. Remove this line if you don't.
command! -bar -nargs=+ -complete=dir CompareDir
            \ tabnew | let t:paths = [<f-args>] | let t:compare_mode = 1 | vsp
            \ | silent exe '1windo lcd ' . t:paths[0] . ' | ' . ' 2windo lcd ' . t:paths[1]
            \ | windo exe 'exe "edit " . getcwd()'

" Pair this command with these autocommands to automatically enable diff mode for
" opened buffers in that tabpage:
augroup CompareDir
    au!
    au BufWinLeave * if get(t:, "compare_mode", 0) | diffoff | endif
    au BufEnter * if get(t:, "compare_mode", 0)
                \ |     if &bt ==# ""
                \ |         setl diff cursorbind scrollbind fdm=diff fdl=0
                \ |     else
                \ |         setl nodiff nocursorbind noscrollbind
                \ |     endif
                \ | endif
augroup END
```

Now, when you call `:CompareDir path/to/folder1 path/to/folder2`, you'll get a new tab page with two windows, each cd-ed into each of the given paths. When you open any normal buffer in any of the windows, diff mode is automatically enabled.

If this does not satisfy your needs you need to explain in more detail how it is functionally different, and what a potential implementation in diffview would look like.

**Comment by ray-x** [comment]
Thanks, your script should solve the question I have ATM.

**Comment by searleser97** [comment]
> @ray-x comparing two files is supported natively in vim. Just open the first file, then `:diffsplit other/file`. See `:h diffsplit` for more info.
> 
> Comparing any two folders is not currently supported. Is this a feature you would like to see implemented?

Will this option use diffview or how will the diff be shown ?
