### ISSUE TITLE
Not highlighting differences properly when using material.nvim colorscheme

### ISSUE THREAD

**Issue by ziombo** [sindrets/diffview.nvim#108]
Self explanatory, when using [material.nvim](https://github.com/marko-cerovac/material.nvim) theme no differences are highlighted. Example screenshots: 
![image](https://user-images.githubusercontent.com/15613606/149392266-c21e6e62-9afe-464b-951d-4a63aa98ecba.png)

Different style of same theme:
![image](https://user-images.githubusercontent.com/15613606/149392136-531f13be-2e6d-4782-98fb-01bcd94d8dcc.png)

Different theme ([onedark ](https://github.com/navarasu/onedark.nvim)with 'deep' style)
![image](https://user-images.githubusercontent.com/15613606/149392308-b3f70f8f-6b4e-4eef-a93d-924857a3cbca.png)

From what I see, there's to highlighting for material theme, only text changes color. Is this an issue with highlights groups?

**Comment by sindrets** [comment]
This is an issue with the color scheme. This plugin uses the normal diff highlights for diff mode. That is: `DiffAdd` `DiffDelete`, `DiffChange` and `DiffText`. Just make sure the color scheme defines these groups.

**Comment by ziombo** [comment]
Thanks for quick response!
