### ISSUE TITLE
Command to scroll views from the file/file_history panel

### ISSUE THREAD

**Issue by smackesey** [sindrets/diffview.nvim#109]
This is a minor quality of life improvement request: typically when I open a diffview, I'm not interacting with the views et al except to scroll. I just want to look at the contents. Currently we have to switch the focused window to perform the scrolling. It would be nice if it were possible to scroll the views directly from the file panel.

**Comment by sindrets** [comment]
@smackesey This is now available as the action `scroll_view({distance})`. New default
keymaps `<c-b>` and `<c-f>` have been mapped to this action in the `file_panel`
and the `file_history_panel`.

```vimhelp
scroll_view({distance})                         *diffview-actions-scroll_view*
        Contexts: `panel`

        Scroll the view a given distance.

        Parameters:~
            {distance} (number)
                Either an exact number of lines, or a fraction of the window
                height. Use negative numbers to scroll up and positive numbers
                to scroll down.
```

Example mapping:

```lua
local actions = require("diffview.actions")
require("diffview").setup({
  keymaps = {
    file_panel = {
      ["a"] = actions.scroll_view(-0.5),  -- Scroll the view up 50% of the current window height.
      ["b"] = actions.scroll_view(30),    -- Scroll the view down 30 lines
    }
  }
})
```

**Comment by Davincible** [comment]
@sindrets Is it possible to lock the scrolling of both pannels? I.e. if I scroll one with either mouse or j/k the other one moves along as well?

**Comment by sindrets** [comment]
@Davincible That's how it already works as long as the cursor is in the window you're scrolling, and you haven't intentionally disabled `'scrollbind'`. This is how `:h 'scrollbind'` works in vim. If you want scrollbind to apply also when the window is not focused, you should look for an issue upstream.
