### ISSUE TITLE
DiffviewOpen into DiffviewToggle?

### ISSUE THREAD

**Issue by thepenguinthatwants** [sindrets/diffview.nvim#11]
Hi Sindre!
Your plugin is amazin looks way more cleanier for me checking diff's than fugitive.
But the problem is that closing multiple buffers manually feels weird, and writing DiffviewClose seems bit hassle.
Is it possible to change this into DiffviewToggle to easily open and close it?

**Comment by rudotriton** [comment]
I was about to write the same suggestion 😄

**Comment by sindrets** [comment]
Glad you like it!
A `:DiffviewToggle` would not make sense, because you can have multiple Diffviews open tracking different (or the same) git revs. What should a toggle do in the scenario where there are multiple views? Just pick the first one? That doesn't sit right with me. But: this is easily implementable with my API. Put this somewhere in your config, and you can call it with `:lua DiffviewToggle()`:

```lua
-- Lua
local last_tabpage = vim.api.nvim_get_current_tabpage()

function DiffviewToggle()
  local lib = require'diffview.lib'
  local view = lib.get_current_diffview()
  if view then
    -- Current tabpage is a Diffview: go to previous tabpage
    vim.api.nvim_set_current_tabpage(last_tabpage)
  else
    -- We are not in a Diffview: save current tabpagenr and go to a Diffview.
    last_tabpage = vim.api.nvim_get_current_tabpage()
    if #lib.views > 0 then
      -- An open Diffview exists: go to that one.
      vim.api.nvim_set_current_tabpage(lib.views[1].tabpage)
    else
      -- No open Diffview exists: Open a new one
      vim.cmd(":DiffviewOpen")
    end
  end
end
```

But you also don't need to close the view every time. You can keep it open and navigate back and fourth with `:tabnext` and `:tabprevious`.

**Comment by thepenguinthatwants** [comment]
Not sure if it's because of barbar, but the tabnext is not working correctly.

**Comment by sindrets** [comment]
> tabnext is not working correctly.

What does that mean? What is not working?

**Comment by sindrets** [comment]
@thepenguinthatwants It sounds like maybe you're a bit confused about the difference between buffers and tabpages? I'm not sure. So just to be clear, at the risk of over-explaining: tabpages in vim are completely independent window layouts, buffers are what modern editors would refer to as "tabs" I suppose.

> The idea would've being opening and checking diff's and then closing and continuing work.

This is possible, and works even better if you don't close the tabpage. Here's a little video demonstration of how I use it (I normally use key bindings to invoke `:tabn` and `:tabp`):


https://user-images.githubusercontent.com/2786478/116927937-a5966e00-ac5c-11eb-82d2-faf09f52d112.mp4

If anything is still unclear, just let me know.

**Comment by harrisoncramer** [comment]
I've setup this shortcut and the call is saying it cannot find the function "get_current_diffview" in the module. Perhaps this function has been renamed?

**Comment by sindrets** [comment]
@harrisoncramer yes, it's been renamed to `get_current_view()` as it now encompasses history views as well.

**Comment by mmirus** [comment]
I modified the above example to be an open/close toggle for a use case where you really do just want that, and don't need the binding to account for multiple open diffviews.

```lua
local last_tabpage = vim.api.nvim_get_current_tabpage()
function DiffviewToggle()
  local lib = require'diffview.lib'
  local view = lib.get_current_view()
  if view then
    -- Current tabpage is a Diffview: go to previous tabpage
    vim.cmd(":DiffviewClose")
  else
    -- No open Diffview exists: Open a new one
    vim.cmd(":DiffviewOpen")
  end
end
```

Thanks all!

**Comment by gennaro-tedesco** [comment]
Another example that I have built, to toggle diff against any branch, that makes use of [fzf-lua](https://github.com/ibhagwan/fzf-lua)
```lua
toggle_diffview = function()
	local lib = require("diffview.lib")
	local view = lib.get_current_view()
	if view then
		vim.cmd.DiffviewClose()
	else
		require("fzf-lua").fzf_exec("git branch -a", {
			prompt = "diff:",
			actions = {
				["default"] = function(selected)
					vim.cmd.DiffviewOpen({ args = { selected[1] } })
				end,
			},
		})
	end
end
```
