### ISSUE TITLE
Can it compare two different local branches?

### ISSUE THREAD

**Issue by tristone13th** [sindrets/diffview.nvim#110]

**Comment by sindrets** [comment]
Yes: `:DiffviewOpen branch-1..branch-2`

**Comment by tristone13th** [comment]
> Yes: `:DiffviewOpen branch-1..branch-2`

It complains about "Bad revision: branch-1..branch-2", where branch-1 and branch-2 are the names of my local branches.

**Comment by sindrets** [comment]
@tristone13th These are two branches on the same repo that exist locally? If so it should work. Try to use `git-rev-parse` to see if git recognizes your branches:

```sh
git rev-parse branch-1
git rev-parse branch-2
git rev-parse branch-1..branch-2
```

Git should return one commit SHA for each of the first two commands, and two commit SHA's for the third. If not, then either one or both of the branches don't exist locally.
