### ISSUE TITLE
Go to next difference

### ISSUE THREAD

**Issue by tristone13th** [sindrets/diffview.nvim#111]
Is it possible to go to the next different place between the two files?

**Comment by gegoune** [comment]
Try `[c` and `]c` It works for me although `:map [c` shows 'No mapping found'.

**Comment by sindrets** [comment]
Yes, exactly what @gegoune said. That's a default binding in vim. It's documented under `:h jumpto-diffs`.

**Comment by tristone13th** [comment]
It worked! Many thanks to you all.

**Comment by louwers** [comment]
Is it possible to automatically move to the next file?

**Comment by sindrets** [comment]
@louwers with `]c`? No. You could do something like this I suppose:

```lua
require("diffview").setup({
  keymaps = {
    view = {
      {
        "n", "]c",
        function ()
          local cursor = vim.api.nvim_win_get_cursor(0)
          vim.cmd("norm! ]c")
          if cursor[1] == vim.api.nvim_win_get_cursor(0)[1] then
            -- The cursor didn't move: go to the next entry
            actions.select_next_entry()
          end
        end,
        { desc = "Next hunk / entry" },
      },
    },
  },
})
```

Keep in mind that if you're using gitsigns with its suggested mappings, it will override this in its `on_attach` callback.

**Comment by louwers** [comment]
Cool 😎
