### ISSUE TITLE
Cursorline has underline when current line is on a diff

### ISSUE THREAD

**Issue by skebanga** [sindrets/diffview.nvim#113]
I am using [onedark](https://github.com/navarasu/onedark.nvim) colorscheme, and diffview with `enhanced_diff_hl` set

```
  vim.opt.fillchars = { diff = " " }

  require('diffview').setup({
    enhanced_diff_hl = true,
  })
```

In the below screenshot you can see my current line is 438, and the cursorline is displayed as a slightly lighter gray background

![image](https://user-images.githubusercontent.com/6157939/151146828-0685f3ad-6426-4ab8-909e-645a14af0bfc.png)

However, when I move the cursor over a diff (in this case my current line is 443, within some *added* lines), the cursorline now includes an underscore.

![image](https://user-images.githubusercontent.com/6157939/151147071-3b369985-b9ac-479d-bf03-2646a7df8238.png)

The only highlight I can see referencing Cursorline is the following:

```
DiffviewCursorLine xxx guibg=#31353f
	Last set from ~/.local/share/nvim/site/pack/packer/start/onedark.nvim/colors/onedark.lua
``

However, modifying `DiffviewCursorLine` only affects the file_browser tab, not the diff view of the source code itself.

If I attempt to get the numeric syntax ID when the cursor is within a diff (`synID(line('.'), col('.'), 1)`), it just returns 0, which isn't helpful in finding the syntax group.

Do you have any idea where this underline is coming from, and how to disable it?

**Comment by sindrets** [comment]
It's  a side effect of how highlights are handled in vim, so there's nothing you can do about it (other than opening a PR upstream). See the upstream issue for details: https://github.com/neovim/neovim/issues/9800. As far as I understand it's matter of highlight precedence. When both the diff highlighting and the cursorline wants to change the bg highlight it's hard coded to resolve to an underline instead.

**Comment by skebanga** [comment]
Ok, understood! Thanks for the explanation and the upstream issue link, very useful! I'll close

**Comment by cameronr** [comment]
For those finding this later, setting `cursorlineopt='number'` for diffview windows will hide the underline:

```lua
    hooks = {
      diff_buf_win_enter = function(bufnr, winid, ctx)
        -- Turn off cursor line for diffview windows because of bg conflict
        -- https://github.com/neovim/neovim/issues/9800
        vim.wo[winid].culopt = 'number'
      end,
    },

```
