### ISSUE TITLE
[Feature Request] `:'<,'>DiffViewFileHistory` file history by lines

### ISSUE THREAD

**Issue by ofirgall** [sindrets/diffview.nvim#114]
First I want to say I'm impressed from the plugin, its very useful!

Feature Description:
Add `:'<,'>DiffViewFileHistory` which will let you see the history of specific line range.
E.g I select line 30 to 50 in `README.md` the git command that will execute behind the scene is `git log -L30,50:README.md` and this will show the history of the lines.

Example of plugin that utilize the `:'<,'>` operator(?): https://github.com/michaelb/sniprun

**Comment by sindrets** [comment]
Yes, this is on my TODO list of features to add so I'll try to get around to it when I get some time to work on this again!

**Comment by sindrets** [comment]
Implemented in the latest commit! See the PR for details.

**Comment by weilbith** [comment]
How do I use this properly with `-L:<function_name>:<file_path>`? When I‘m trying this, I get the correct commits. So only those which touched this function. I compare this to the output of Git on the console. But I still see the full diff of the file for each commit. In the console I correctly see only a single hunk for the function defined. 
How to make this possible for Diffview too?
Thanks for your help!

**Comment by weilbith** [comment]
Ah. Damn. Would have been too cool. 😕
Thanks for the input.

**Comment by weilbith** [comment]
Do you think it is worth opening an issue for this? Or would this be out of scope for this plugin?

**Comment by sindrets** [comment]
@weilbith Sure, I'm interested in at least exploring the idea. If `foldmethod=manual` behaves properly in diff-mode, this should be quite feasible.

**Comment by sindrets** [comment]
@weilbith Implemented in #323.
