### ISSUE TITLE
`DiffViewFileHistory` with commit range

### ISSUE THREAD

**Issue by ofirgall** [sindrets/diffview.nvim#115]
Add `git rev` argument for `DiffviewFileHistory` like `DiffviewOpen` has.

This will let us scan through the diffs between 2 commits but with the commits separated.

**Comment by sindrets** [comment]
This is a good idea, and it should be pretty simple to implement. The only thing that makes me hesitate is that I think it's gonna require a breaking change to the file history command to avoid ambiguity between git rev args and path args. It probably needs to change to something like:

```
:DiffviewFileHistory [git-rev] [args] [ -- {paths...}]
```

**Comment by ofirgall** [comment]
Thanks for the quick reply!

I understand the concern, as I see it if you want avoid breaking the API you can add another command if you prefer it, something like `DiffviewHistory` or `DiffviewLog` (because its kinda like `git log` but with nice UI), or you can add it as arg `--git_rev` which is not very intuitive.

**Comment by sindrets** [comment]
@ofirgall I ended up going with a flag option to avoid breaking changes. Regardless, you can now specify commit ranges with the `--range` flag like so:

```
:DiffviewFileHistory --range={git-rev}
```

**Comment by ofirgall** [comment]
Thanks a lot for developing this plugin, It helps me alot!
