### ISSUE TITLE
[Question] Any way to map `l` and `h` to expand/collapse entry in File History window

### ISSUE THREAD

**Issue by fanliver** [sindrets/diffview.nvim#118]
Pressing `l` and `h` in the File History window (`:DiffViewFileHistory`) moves the cursor to the right/left.
Is there any way to map `l` and `h` to expand/collapse the entry?

I tried mapping `l` with `cb("select_entry")` but it didn't work.
```
    file_panel = {
      ["l"]             = cb("select_entry"),
    }
```

**Comment by sindrets** [comment]
The `file_panel` mappings are only used in the normal `:DiffviewOpen` view. You should be changing the `file_history_panel` mappings. The two panels have separate mappings.

**Comment by sindrets** [comment]
@fanliver Do you have any other questions, or can this issue be closed?

**Comment by fanliver** [comment]
@sindrets Thanks, it can be closed.
