### ISSUE TITLE
Open in project working directory rather than local working directory

### ISSUE THREAD

**Issue by tristone13th** [sindrets/diffview.nvim#119]
I think we should add an option to make DiffViewOpen open in the folder with respect to pwd rather than the local working directory.

**Comment by sindrets** [comment]
I was a bit quick with the label here. I realized this already exists in the form of the `-C` flag. If you do `:DiffviewOpen -C.` it will use your pwd rather than your local working dir. If you want this to be default behavior just add it to your default args:

```lua
default_args = {
  DiffviewOpen = { "-C." },
},
```

**Comment by tristone13th** [comment]
> 

It works, many thanks!
