### ISSUE TITLE
Option to specify `goto_file` split between horizontal + vertical

### ISSUE THREAD

**Issue by marcoppenheimer** [sindrets/diffview.nvim#120]
Current behavior calls `sp` which will default to a horizontal split. Wasn't able to find a way around this to meet screen size.

Propose adding an unused mapping for a `goto_file_vsplit` calling `vim.cmd("vs " .. vim.fn.fnameescape(file.absolute_path))`

**Comment by sindrets** [comment]
The `goto_file` mappings are meant to loosely mimic vim's default `:h gf` mappings. Can you not just use normal window commands to move the split window? I.e. `<C-W>L` to move the window to the far right. If you need more nuanced window shifting, you could check out my other plugin [winshift.nvim](https://github.com/sindrets/winshift.nvim).

Note that you can add additional window commands etc. to the mapping like so:

```lua
key_bindings = {
  view = {
    ["<C-w><C-f>"] = cb("goto_file_split") .. " <Cmd>wincmd L<CR>",
  }
}
```
