### ISSUE TITLE
Can I tell DiffviewOpen to start with the diff of the file that I'm currently inside?

### ISSUE THREAD

**Issue by melkster** [sindrets/diffview.nvim#121]
`DiffviewOpen` seems to always show me the diff of the first file in the file panel. Is it possible to start the diff view of the current file that I am inside when calling `DiffviewOpen`? I feel like this is a more intuitive behaviour. It could fall back to showing me the first file in the panel if the current buffer is not an edited file.

**Comment by sindrets** [comment]
This is now the default behavior. You can now also specify a different preferred initially selected file like so:

```
:DiffviewOpen --selected-file=foo/bar/baz
```
