### ISSUE TITLE
Vim(doautocmd):E518 error on :DiffviewFileHistory

### ISSUE THREAD

**Issue by wookayin** [sindrets/diffview.nvim#123]
The command I tried: `:DiffviewFileHistory ./`, and I see an error:

```
Error executing vim.schedule lua callback: .../diffview.nvim/lua/diffview/views/file_entry.lua:236: Vim(doautocmd):E518: Unknown option: Do    
stack traceback:
        [C]: in function 'cmd'
        .../plugged/diffview.nvim/lua/diffview/views/file_entry.lua:236: in function 'load_buffers'
        ...im/lua/diffview/views/file_history/file_history_view.lua:136: in function 'set_file'
        ...im/lua/diffview/views/file_history/file_history_view.lua:53: in function 'callback'
        ...m/lua/diffview/views/file_history/file_history_panel.lua:228: in function <...m/lua/diffview/views/file_history/file_history_panel.lua:190>
```

The line 236 in `file_entry.lua` is indeed strange. it reads:

```
  vim.cmd("do WinEnter")
```
I guess you meant `:doautocmd`, which occurs a few times throughout the code. 
**UPDATE**: `:do` is an alias for `:doautocmd`, so it should be fine? But not sure why such error happens.

I tried replacing all the occurences of `vim.cmd "do ...` with `vim.cmd "doautocmd`, but still it doesn't fix the problem; I see  another error message:

```
Error executing vim.schedule lua callback: .../diffview.nvim/lua/diffview/views/file_entry.lua:236: \
Vim(doautocmd):E518: Unknown option: Use 
```
or
```
Vim(doautocmd):E518: Unknown option: Remove
```
Not sure where `use` or `remove` does come from.

Neovim version: `v0.7.0-dev+1283-g77eb6f9dc`

**Comment by sindrets** [comment]
I can't reproduce this. This is probably related to your config. `:do [event]` will trigger any autocommand subscribed to `[event]`, including your custom autocommands and any autocommands registered by your installed plugins. The stack trace only indicates that something went wrong while executing the callbacks for the autocommand.

Try to reproduce this with a minimal config. [Here's a template](https://gist.github.com/sindrets/3e671e79ce4566667f9ec176786dfadd).

**Comment by wookayin** [comment]
I actually was reminded of a similar bug in another plugin https://github.com/rbong/vim-flog/issues/61 : it is related to modeline. When a commit message contains some string like `vim: ...`, it will try to parse and execute it.

Therefore, the fix would be you add the `setlocal nomodeline` option for the diffview filehistory buffer.

**Comment by sindrets** [comment]
Good catch! It didn't occur to me that the commit messages could trigger the modeline. You're right, of course: modelines should not be enabled in these buffers. I'll fix this soon.

**Comment by wookayin** [comment]
Thank you! Can confirm that this now has been fixed.
