### ISSUE TITLE
[feature] DiffViewOpen support a single file

### ISSUE THREAD

**Issue by leisiji** [sindrets/diffview.nvim#13]
I found that DiffViewOpen only support dir. Sometimes I only want to diff the current file that I an editing. Can DiffViewOpen add support for the diff of a single file with files panel off?

**Comment by sindrets** [comment]
If you only want to diffsplit a single file, most git wrappers for vim provide this functionality. Example from [Fugitive](https://github.com/tpope/vim-fugitive): `:Gdiffsplit`.

But if you want to do this with Diffview, it's simple to set up a custom command. `:DiffviewOpen` lets you narrow down what files are shown by using the optional path args. Please see the documentation for further details.

Here is a command that does what you want:

```vim
" vimscript
command! DiffviewFile execute("DiffviewOpen -- " . expand("%")) | DiffviewToggleFiles
```

Add this to your config, and then you can call it with `:DiffviewFile`.

**Comment by leisiji** [comment]
Thanks for your quick reply. The method works well.
