### ISSUE TITLE
[Diffview.nvim] The action 'select' does not exist!

### ISSUE THREAD

**Issue by TamaMcGlinn** [sindrets/diffview.nvim#138]
The latest commit, 9359f7b, does not work for me. I believe the problem is that select is a keyword in lua, and you have attempted to use it as a variable name. When I start up, having pasted in the new README section's configuration to my vimrc, I get the error in the title.

After reverting (and again, matching my configuration to that in the README) it works again.

**Comment by sindrets** [comment]
`select` is not a keyword in lua, it's just the README that's wrong. Sorry about that. It's right in the default config in the code though. It should be `select_entry`.

But you don't need to define keymaps if you're not changing the default values. The plugin will merge your mappings with the defaults unless you use `keymaps.disable_defaults = true`.

I'll fix the typo in the README later when I'm not on my phone. Thanks for bringing my attention to it.
