### ISSUE TITLE
[Question] Change the default behavior of the stage keymap (-)

### ISSUE THREAD

**Issue by tuxflo** [sindrets/diffview.nvim#139]
When I'm done with my changes I want to use Diffview to go through all of my changes step by step, check the diffs and stage them.
Currently, if I stage a file using `-` the cursor jumps from "Changes" down to "Staged changes" with the previously selected file. Then I have to press Tab or S-Tab lots of times to go back to the "next" untracked file from the "Changes" list.

So is it possible to change `-` to stage the file but then jump to the next unstaged file in the list?

**Comment by sindrets** [comment]
Yes, I think it should do this by default. I've long thought that it's frustrating the way the cursor jumps when you stage files. I'll see if I can look into this soon.

**Comment by sindrets** [comment]
@tuxflo Can you give this another try on the latest commit? The cursor should move a lot more reasonably compared to before. The strategy is now:

- If the file being staged is currently open in the view: open, and bring the cursor to the next file.
- Otherwise, leave the cursor alone.

**Comment by tuxflo** [comment]
It somewhat works now, depending on how one would define "next file"
For example if my change tree looks like this:
![image](https://user-images.githubusercontent.com/2816893/170240853-070a03ff-dbb7-433f-843e-bb89adea750a.png)
and I stage the file `angular.json` I'd expect to open the file `tsconfig.json` after staging.
However it opens the file `environment.dev.ts` so I guess the "next file detection" isn't folder aware yet.
But its still better then before, thanks a lot for working on it so quickly.

**Comment by sindrets** [comment]
The way you describe is how it's supposed to work, as long as the file you're staging is open in the view (you can see it's diff):

https://user-images.githubusercontent.com/2786478/170247128-7455f274-a62b-48ae-a3e2-4d8c421ac58f.mp4

If the file is *not* open in the view, the cursor will be left alone.

**Comment by tuxflo** [comment]
Ah I missed the part "is currently open in the viewer" if I select it, it works as expected.
Thanks again 👍

**Comment by sindrets** [comment]
@tuxflo I think you're right in expecting it should work regardless of whether or not the file is open in the view. This should be addressed now in one of the latest commits.
