### ISSUE TITLE
strange issue: all files displayed as staged

### ISSUE THREAD

**Issue by emmanueltouzery** [sindrets/diffview.nvim#141]
Hi, first off, thank you very much for you plugin, i love it!

Now for my question. I am changing my neovim setup and on my new setup something is behaving very strangely with diffview, and I don't understand what. The symptoms is that when I run `require('diffview').open()`, all the files of the project are shown as staged, even if they're not staged.
So that means that some files are shown twice, both in the "Changes" and in the "Staged changes". But that happens only if i have nothing staged. The moment I stage a file, then the display is correct, and only the truly staged files are displayed as staged.

The output of `git status` and the behavior of `neogit` are normal, I see this on all the git repos on which I tested, and what's more, diffview behaves correctly on my old neovim setup. So I'm quite confused. Do you have any idea what could cause this?

**Comment by sindrets** [comment]
> Hi, first off, thank you very much for you plugin, i love it!

@emmanueltouzery I'm glad to hear!

This issue sounds strange. Could you please provide your diffview config, and relevant output from `:DiffviewLog` right after you reproduce this behavior. Please also make sure you're on the latest version, as I very recently made the log output more detailed.

**Comment by emmanueltouzery** [comment]
well, upgrading the version fixed it. I was on a recent version though (just a few commits behind), and another installation with the same version didn't have the issue. To be honest, I was half-suspecting that the packer compilation would have messed up something, but deleting the compiled packer file didn't help. I don't know. But I think whatever it was, it wasn't diffview. Certainly if I reproduce I'll reopen this bug or something, but I doubt I will.
