### ISSUE TITLE
[Question] go to file always opened in splited window

### ISSUE THREAD

**Issue by LintaoAmons** [sindrets/diffview.nvim#147]
When I am in Diffview, using the `go to file` action will always open the file in the horizontal split window. 

Is there an option that I can set for this? To open the file in the whole window(it didn't split).

**Comment by LintaoAmons** [comment]
I was thinking is it possible to open the diff view in the current buffer and when `go to file`, the file will open in the current buffer too.

**Comment by sindrets** [comment]
@LintaoAmons I believe `:h diffview-actions-goto_file_edit` is what you're looking for.

**Comment by sindrets** [comment]
@LintaoAmons Can I consider this issue as resolved, or do you have any other questions?

**Comment by LintaoAmons** [comment]
Yeah~ Thx for your reply
