### ISSUE TITLE
Command/mapping to move between hunks 

### ISSUE THREAD

**Issue by danielo515** [sindrets/diffview.nvim#148]
Hello, thanks for this extension, it is great!

Something I got used to while using lazygit is moving between hunks in the diff view. It will be awesome if you provide a command that can be mapped to your preferred key and move between hunks in the diff view file faster .

Regards

**Comment by danielo515** [comment]
Wow, I had no idea! #131 was helpful too.
Many thanks .

**Comment by sindrets** [comment]
No worries! I should probably mention some of these help pages in the README. This seems to be a part of vim that many people are unfamiliar with.

**Comment by ovidius72** [comment]
How can we remap the next/prev hunk keybinding? I already have [c and ]c mapped. Thanks

**Comment by sindrets** [comment]
@ovidius72 yes:

```lua
keymaps = {
  view = {
    ["[c"] = "[c",
    ["]c"] = "]c",
  },
}
```

**Comment by ovidius72** [comment]
> @ovidius72 yes:
> 
> ```lua
> keymaps = {
>   view = {
>     ["[c"] = "[c",
>     ["]c"] = "]c",
>   },
> }
> ```

thanks a lot.
