### ISSUE TITLE
Deleted lines character/icon

### ISSUE THREAD

**Issue by ziombo** [sindrets/diffview.nvim#149]
How can I achieve the same 'lines deleted' like here: 
![image](https://user-images.githubusercontent.com/15613606/172023827-23bb33a2-1ddb-4fa6-9c0f-7fb97d177fe9.png)

What I have right now are just dashes --------
![image](https://user-images.githubusercontent.com/15613606/172023834-033e41d5-98ef-4229-b920-0685bd7e8dd1.png)

**Comment by sindrets** [comment]
See the the bottom of the README, or #35.

**Comment by ziombo** [comment]
Perfect. 

I see on the screenshots that you're also using relative line numbers. Do you have an idea how could I change them to normal line numbers for DiffView only? 
Not sure if asking here's fine or if I should create a new issue for this.

**Comment by sindrets** [comment]
Yes, see `:h diffview-config-hooks`. The `diff_buf_read` hook works for this. There
are examples in the docs for how to change local options in diff buffers only.

**Comment by ziombo** [comment]
Works perfectly. Thanks
