### ISSUE TITLE
Need a method to specify git executable path

### ISSUE THREAD

**Issue by pr-313** [sindrets/diffview.nvim#158]
For people working on old RHEL OSs, it's common to have to compile tools for yourself from the source. And since its enterprise, I cannot impact the main git bin file. Adding an option (similar to fugitive's let g:fugitive_git_executable) would help make use of the --diff-merge option. Else :DiffviewFileHistory just fails with git version 2.18.0

`  2 [ERROR Fri 17 Jun 2022 11:01:14 AM IST] ...arati/.vim/plugged/diffview.nvim/lua/diffview/logger.lua:42: [system_list()] Job exited with a non-zero exit status! Code: 128                                                                 
  1 [ERROR Fri 17 Jun 2022 11:01:14 AM IST] ...arati/.vim/plugged/diffview.nvim/lua/diffview/logger.lua:42: [system_list()]    [cmd] git 'log' '--pretty=format:%H' '--name-status' '-n1' '--diff-merges=first-parent' '--'                   
132 [ERROR Fri 17 Jun 2022 11:01:14 AM IST] ...arati/.vim/plugged/diffview.nvim/lua/diffview/logger.lua:42: [system_list()] [stderr] fatal: unrecognized argument: --diff-merges=first-parent    `

**Comment by sindrets** [comment]
You can now configure this with `git_cmd` in the config. See the PR for details.
