### ISSUE TITLE
[Question]: Bare repo `--git-dir` and `--work-tree`

### ISSUE THREAD

**Issue by lmburns** [sindrets/diffview.nvim#163]
I track my dotfiles with a program that uses a bare repository, and for each of its `git` commands, it uses the following:
```bash
git --git-dir="$DOTBARE_DIR" --work-tree="$DOTBARE_TREE"
```

Whenever I try to use `DiffviewOpen` with the `-C` flag, I use the value of the variable `$DOTBARE_DIR` (i.e., `:DiffviewOpen -C/home/lucas/.local/share/dotfiles`) and I get the following error:
```vim
Error executing Lua callback: .../opt/diffview.nvim/lua/diffview/views/diff/diff_view.lua:79: attempt to concatenate field 'git_dir' (a nil value)
stack traceback:
        .../opt/diffview.nvim/lua/diffview/views/diff/diff_view.lua:79: in function 'post_open'
        ...ack/packer/opt/diffview.nvim/lua/diffview/views/view.lua:47: in function 'open'
        ...site/pack/packer/opt/diffview.nvim/lua/diffview/init.lua:159: in function 'open'
        ...m/site/pack/packer/opt/diffview.nvim/plugin/diffview.lua:23: in function <...m/site/pack/packer/opt/diffview.nvim/plugin/diffview.lua:22>
```

However, if I open a directory that is not a bare repository, it works just fine. I was wondering if there was already a way to view my dotfiles repository, and if not, could this be a feature that is implemented?

**Comment by sindrets** [comment]
@lmburns I use a bare git repo to track dotfiles myself, and the way I handle this is by using git's environment variables:

```lua
vim.env.GIT_WORK_TREE = vim.fn.expand("~")
vim.env.GIT_DIR = vim.fn.expand("~/.dotfiles")
```

The plugin will use your environment, so all git env vars are respected.

> Whenever I try to use `DiffviewOpen` with the `-C` flag, I use the value of the variable `$DOTBARE_DIR`

It seems like you are trying to use the `-C` flag as git's `--git-dir` flag? That is not what it's for. The `-C` flag is effectively the same as git's `-C` flag (`man git(1)`): it will run git commands with the given path as the current working directory.

But the stack trace you provided is interesting. This seems like an unrelated bug. It looks like the plugin was able to find a top-level of some repository, but not its git dir. Could you please provide relevant information from `:DiffviewLog` after this happens? Please also update the plugin before you do so, as I just now pushed a commit that makes the logs more verbose.

**Comment by lmburns** [comment]
Awesome, I wasn't aware of the environment variable thing. I got the dotfiles thing working.

After updating the plugin, me being in the same directory and running the same two commands here is what happens. 

I am in `$XDG_CONFIG_HOME/nvim/lua`.
- When running something like `:DiffviewOpen -C/home/lucas/projects/github/wutag`, which is a regular repository, everything works fine. The panel is opened up as if I was in that directory.
- When running a command that resolves to a bare repository (i.e,. `:DiffviewOpen -C/home/lucas/.local/share/dotfiles`, I get a similar error:
```vim
E5108: Error executing lua ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua
:83: Vim:Error executing Lua callback: .../opt/diffview.nvim/lua/diffview/views/diff/diff_view.lua:79: attempt to concatenate field 'git_dir' (a nil value)
stack traceback:
        [C]: in function 'cmd'
        ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: in function <...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:161>
        [string ":lua"]:1: in main chunk
```

<details>
<summary>`:DiffviewLog` output</summary>
```log
[ERROR Thu 23 Jun 2022 08:27:45 PM CDT] ...te/pack/packer/opt/diffview.nvim/lua/diffview/logger.lua:42: [system_list()] Job exited with a non-zero exit status! Code: 128
[ERROR Thu 23 Jun 2022 08:27:45 PM CDT] ...te/pack/packer/opt/diffview.nvim/lua/diffview/logger.lua:42: [system_list()]    [cmd] git 'rev-parse' '--path-format=absolute' '--git-dir'
[ERROR Thu 23 Jun 2022 08:27:45 PM CDT] ...te/pack/packer/opt/diffview.nvim/lua/diffview/logger.lua:42: [system_list()]    [cwd] .
[ERROR Thu 23 Jun 2022 08:27:45 PM CDT] ...te/pack/packer/opt/diffview.nvim/lua/diffview/logger.lua:42: [system_list()] [stderr] fatal: not a git repository (or any of the parent directories): .git
[ERROR Thu 23 Jun 2022 08:27:45 PM CDT] ...te/pack/packer/opt/diffview.nvim/lua/diffview/logger.lua:42: [system_list()] Job exited with a non-zero exit status! Code: 128
[ERROR Thu 23 Jun 2022 08:27:45 PM CDT] ...te/pack/packer/opt/diffview.nvim/lua/diffview/logger.lua:42: [system_list()]    [cmd] git 'rev-parse' '--show-toplevel'
[ERROR Thu 23 Jun 2022 08:27:45 PM CDT] ...te/pack/packer/opt/diffview.nvim/lua/diffview/logger.lua:42: [system_list()]    [cwd] .
[ERROR Thu 23 Jun 2022 08:27:45 PM CDT] ...te/pack/packer/opt/diffview.nvim/lua/diffview/logger.lua:42: [system_list()] [stderr] fatal: not a git repository (or any of the parent directories): .git
[ERROR Thu 23 Jun 2022 08:27:47 PM CDT] ...te/pack/packer/opt/diffview.nvim/lua/diffview/logger.lua:42: [system_list()] Job expected output, but returned nothing! Code: 128
[ERROR Thu 23 Jun 2022 08:27:47 PM CDT] ...te/pack/packer/opt/diffview.nvim/lua/diffview/logger.lua:42: [system_list()]    [cmd] git 'rev-parse' 'HEAD' '--'
[ERROR Thu 23 Jun 2022 08:27:47 PM CDT] ...te/pack/packer/opt/diffview.nvim/lua/diffview/logger.lua:42: [system_list()]    [cwd] /home/lucas
[ERROR Thu 23 Jun 2022 08:27:47 PM CDT] ...te/pack/packer/opt/diffview.nvim/lua/diffview/logger.lua:42: [system_list()] [stderr] fatal: not a git repository (or any of the parent directories): .git
[ERROR Thu 23 Jun 2022 08:27:47 PM CDT] ...te/pack/packer/opt/diffview.nvim/lua/diffview/logger.lua:42: [system_list()] Job exited with a non-zero exit status! Code: 128
[ERROR Thu 23 Jun 2022 08:27:47 PM CDT] ...te/pack/packer/opt/diffview.nvim/lua/diffview/logger.lua:42: [system_list()]    [cmd] git 'rev-parse' '--path-format=absolute' '--git-dir'
[ERROR Thu 23 Jun 2022 08:27:47 PM CDT] ...te/pack/packer/opt/diffview.nvim/lua/diffview/logger.lua:42: [system_list()]    [cwd] /home/lucas
[ERROR Thu 23 Jun 2022 08:27:47 PM CDT] ...te/pack/packer/opt/diffview.nvim/lua/diffview/logger.lua:42: [system_list()] [stderr] fatal: not a git repository (or any of the parent directories): .git
```
</details>

However, if I do what you had mentioned above and set environment variables in my neovim configuration, I am able to run the above command on that bare repository and it opens just fine.

**Comment by sindrets** [comment]
@lmburns I'm confused by how this error is even able to occur. Something to do with symlinks, maybe? When I run `:DiffviewOpen -C/foo/bar/baz` and `/foo/bar/baz` is a bare git repo, the plugin gives me the message:

```
[Diffview.nvim] Path not a git repo (or any parent): "/foo/bar/baz"
```

And I can see in the log that the `rev-parse --show-toplevel` failed with `[stderr] fatal: this operation must be run in a work tree`, which is what I would expect.

But from the description you give, and the log output you provided (assuming this is the log output produced by calling `:DiffviewOpen -C/home/lucas/.local/share/dotfiles`), it seems like the plugin was able to successfully run `rev-parse --show-toplevel`, but then - confusingly - fails to later run `rev-parse --git-dir`.

Did you set the git environment variables before producing this log output? If so, that might explain what happened here, because the environment variables will take priority over the `-C` flag in the plugin. This was the only way I was able to reproduce this issue. Perhaps some other program had set `$GIT_WORK_TREE` on your system?

Regardless, after the latest commit, you should get notified by the plugin if it was unable to find both the top-level as well as the git-dir.

**Comment by lmburns** [comment]
When setting the git environment variables, no I don't get any error. That's what I had meant in the last paragraph/section of my last comment. If you aren't able to reproduce this issue, I wouldn't consider it to be a big deal. I can't think of a reason why I would be running the above command if it weren't to my dotfiles repository. And I have done what you said and set the git environment variables, which does exactly what I want it to do.

Because of that, I will go ahead and close this issue. Thank you for your help.
