### ISSUE TITLE
File history shows the compared (last comimitted) file with wrong hash number

### ISSUE THREAD

**Issue by zjp-CN** [sindrets/diffview.nvim#166]
The project in snapshot is [here](https://github.com/zjp-CN/nvim-config/commits/main).

File history show the last comimitted file path with wrong hash number: [`#71b7`](https://github.com/zjp-CN/nvim-config/commits/main) clearly didn't commit [`lua/plugins.lua`](https://github.com/zjp-CN/nvim-config/blob/main/lua/plugins.lua).

![image](https://user-images.githubusercontent.com/25300418/175984455-b44897ff-a753-4371-8d93-a3a69cebe8d7.png)

![image](https://user-images.githubusercontent.com/25300418/175986605-c9e2e8f1-9e8e-4f5c-b206-76c7029c7d2e.png)

**Comment by sindrets** [comment]
@zjp-CN I think you have misunderstood what the file history view is diffing. It's diffing the state of the target file(s) in the selected commit (on the right), against the state of the file(s) in said commit's parent commit (on the left).

In your example, `833a64643036aa9a41bad1bc4bebb340e020afe4` was the commit that changed `lua/plugins.lua`, and `833a646`'s parent commit is `71b7b0e28039c5636f9b51a0205fb2dbdf48b190`. Thus, that is what it compares against.

![image](https://user-images.githubusercontent.com/2786478/176005330-ccb7d068-fd0b-428d-bd42-b3291056141f.png)

**Comment by zjp-CN** [comment]
Thank you for the explantion and the great tool!
