### ISSUE TITLE
[Feature] allow keybinds in the commit_log_panel

### ISSUE THREAD

**Issue by jemag** [sindrets/diffview.nvim#167]
For example:
```lua
    commit_log_panel = {
      ["q"]     = actions.close,
    },

```

**Comment by sindrets** [comment]
@jemag The commit log panel is not interactive, it's just a window. Just use whatever mapping you normally use for closing windows (if you use any). If you want a special mapping for closing that particular window, you should use an autocommand:

```vim
au BufWinEnter diffview://*/log/*/commit_log nnoremap <buffer> q <Cmd>q<CR>
```

**Comment by jemag** [comment]
Thanks, I will use that

**Comment by briandipalma** [comment]
```lua
 option_panel = {
      { "n", "q",     actions.close,  { desc = "Close the panel" } },
    },
    help_panel = {
      { "n", "q",     actions.close,  { desc = "Close help menu" } },
    },
```

The other panels close with "q" so surely for consistency the commit_log one should too?
