### ISSUE TITLE
[Feature] action to view current keybinds

### ISSUE THREAD

**Issue by jemag** [sindrets/diffview.nvim#168]
There is quite a lot of mappings that are possible and, unfortunately, I have a terrible memory.

It could be nice to have an action that would show all the current keybinds for the current context (depending on whether we are in the view, file_panel, file_history_panel, etc). Something like `actions.show_keymaps`

<details>
<summary><b>Examples:</b></summary>

For example, with Neotree pressing `?` will show 

![image](https://user-images.githubusercontent.com/7985687/177047522-f31cfea9-8966-404e-945c-939d2eb3b564.png)

Or similar thing in Undotree:

![image](https://user-images.githubusercontent.com/7985687/177047557-f1edec74-b99b-4d4a-854a-d3b2757723de.png)

</details>

**Comment by sindrets** [comment]
@jemag An implementation with a floating window could possibly be nicer. But in the meantime you could add these mappings:

```lua
require('diffview').setup({
  keymaps = {
    file_panel = {
      ["?"] = "<Cmd>h diffview-maps-file-panel<CR>",
    },
    file_history_panel = {
      ["?"] = "<Cmd>h diffview-maps-file-history-panel<CR>",
    },
  }
})
```

Although, I noticed that the documentation for the mappings is outdated, and it's missing some of the new keymaps.

I don't think I'm gonna find time to work on this anytime soon, so if you're willing to contribute a PR - either updating the documentation, or implementing a custom help popup - I would greatly appreciate it.
