### ISSUE TITLE
DiffviewOpen rev does not work

### ISSUE THREAD

**Issue by tamlok** [sindrets/diffview.nvim#172]
Hi,

`DiffviewOpen abcd` should show the contents of the revision `abcd`, right? But I always get 0 changes result after this command.

Is there anything I miss?

Thanks!

**Comment by sindrets** [comment]
> `DiffviewOpen abcd` should show the contents of the revision `abcd`, right?

@tamlok Not quite. That command should compare the current working tree to `abcd`. `:DiffviewOpen abcd^!` would be only the changes in `abcd`.

> But I always get 0 changes result after this command.

Does `abcd` exist locally? If that's a revision from a remote branch, you need to fetch it first. What's the output of `git show -s --oneline abcd`? That should output an abbreviated commit SHA as well as the commit message if `abcd` exists locally.

Lastly, please provide any relevant output from `:DiffviewLog`.

**Comment by tamlok** [comment]
`DiffviewOpen abcd^!` is what I want! I just want to achieve what `git show abcd` works.

Thanks for the great work! Now I could use Vim to read the PR changes!
