### ISSUE TITLE
[question] How to diff with a branch

### ISSUE THREAD

**Issue by eshepelyuk** [sindrets/diffview.nvim#175]
Hello

I can not figure out how to open a diff view for a current file and the file from another branch, so that current file is open to write, so i can pick up certain parts from the branch in UI mode.

I can open view with another branch  using `DiffviewFileHistory % --base=<branch>` but the current file buffer is read only, so I cant modify it.

**Comment by sindrets** [comment]
@eshepelyuk If I understand you correctly, that should be:

```
:DiffviewFileHistory % --base=LOCAL --range=<branch>
```

From `:h :DiffviewFileHistory`:

```vimhelp
        --base={git-rev}
                        Specify a base git rev from which the right side of
                        the diff will be created. Use the special value
                        `LOCAL` to use the local version of the file.

        --range={git-rev}
                        Show only commits in the specified revision range.
```

**Comment by sindrets** [comment]
If you don't need the history, you can also do:

```
:DiffviewOpen <branch> -uno -- %
```

**Comment by eshepelyuk** [comment]
Thnx, i will try this.

May I aslo ask, why `%` is always mandatory when using `DiffviewFileHistory`. I remember in the past this command opened a history for a current file, but now it does not and show some "generic" history instead.

**Comment by eshepelyuk** [comment]
Sorry, thank you.

**Comment by sindrets** [comment]
No need to apologize. I only meant to direct you to the information you inquired about :)
