### ISSUE TITLE
[feature] Allow specifying window-local options in `win_config`

### ISSUE THREAD

**Issue by ceuk** [sindrets/diffview.nvim#178]
To allow customisation of the stausline in the file panel win

e.g. 

```lua
{
  type = "split",
  statusline = " "
}
```

..would essentially disable the statusline for the file panel 

--

I can have a crack at implementing this if I get a sec

**Comment by sindrets** [comment]
@ceuk Are you still interested in implementing this?

**Comment by ceuk** [comment]
Hey, yeah, got a few hours of downtime so going to see if I can get it done now

**Comment by ceuk** [comment]
@sindrets is it worth giving `bufopts` the same treatment do you reckon?
