### ISSUE TITLE
diffviewfilehistory without range broken?

### ISSUE THREAD

**Issue by emmanueltouzery** [sindrets/diffview.nvim#179]
since 16c3985581ee65bccdfbebbe014b24a01adc7d1f (the latest commit as I'm writing this), `require'diffview'.file_history()` doesn't work for me anymore, it fails with:
```
E5108: Error executing lua ...ite/pack/packer/start/diffview.nvim/lua/diffview/lib.lua:224: bad argument #1 to 'format' (number expected, got nil)
stack traceback:
	[C]: in function 'format'
	...ite/pack/packer/start/diffview.nvim/lua/diffview/lib.lua:224: in function 'file_history'
	...te/pack/packer/start/diffview.nvim/lua/diffview/init.lua:170: in function 'file_history'
	[string ":lua"]:1: in main chunk
```

was that intended? Should I change the way I invoke file history after this commit? Looking at the commit message, I'd have thought that not?

**Comment by sindrets** [comment]
@emmanueltouzery The plugin's internal lua API has never been documented nor recommended for use by users. As such, it holds no promise with regards to breaking changes. As described in both the README, and the docs, users are intended to use the command interface through `:DiffviewFileHistory` etc. You can call this from lua with `vim.cmd("DiffviewFileHistory")`.

If you still choose to use the internal, undocumented API, you're on your own with regards to following changes in the code.

If you wish for a stable lua API, you can open a new issue where we can discuss this.

**Comment by emmanueltouzery** [comment]
hmm, my bad, I didn't realize the lua api was unsupported. I found it _slightly_ nicer to call when giving parameters from `vim.keymap.set()`, eg

```diff
- vim.keymap.set("n", "<leader>gL", "<cmd>lua require'diffview'.file_history(cur_file_project_root())<cr>", {desc="project_history"})
+ vim.keymap.set("n", "<leader>gL", "<cmd>lua vim.cmd('DiffviewFileHistory ' .. cur_file_project_root())<cr>", {desc="project_history"})
```

But it's reaaally no biggie. Thanks for the help (and the plugin!).
