### ISSUE TITLE
How to create new user command that leverages builtin completion

### ISSUE THREAD

**Issue by eshepelyuk** [sindrets/diffview.nvim#180]
Hello

Is it possible to achieve a title of the issue ?

For example, I want to create a custom command with a single parameter `DiffLocal <BRANCH>`, that is eventually transformed to `DiffviewFileHistory % --base=LOCAL --range=<BRANCH>`.

But the same time I want to leverage plugins's autocompletion, so after typing `:DiffLocal ` - i would recieve completion candidates list with available branches.

**Comment by sindrets** [comment]
You can currently do something like this:

```lua
vim.api.nvim_create_user_command("DiffLocal", function(state)
  vim.cmd(("DiffviewFileHistory %% --base=LOCAL --range=%s"):format(state.fargs[1]))
end, {
  nargs = "?",
  complete = function(arg_lead, cmd_line, cur_pos)
    return require("diffview").rev_completion(arg_lead, { accept_range = true })
  end,
})
```

**Comment by eshepelyuk** [comment]
Hello @sindrets 

The code works great.
Would you mind adding it as an inspiration/example to FAQ ?

**Comment by eshepelyuk** [comment]
> Hello @sindrets
> 
> The code works great. Would you mind adding it as an inspiration/example to FAQ ?

Hello @sindrets 
Do you think this snippet can be added to a FAQ ?

**Comment by sindrets** [comment]
@eshepelyuk Sorry for the late response. I didn't have time to respond when I first saw your message, and then I forgot about it.

I don't want to add this to the FAQ, because the internal lua API used by the plugin is undocumented, and offers no promise of stability. If a stable lua API is wanted, please open a new issue, and then we can discuss it there.

**Comment by eshepelyuk** [comment]
I understand your point. Let's not overcomplicatte things then :)
closing the issue
