### ISSUE TITLE
Error on `require("diffview").setup {}`

### ISSUE THREAD

**Issue by Nexmean** [sindrets/diffview.nvim#182]
I'm trying to setup diffview using packer.nvim:
```lua
use {
  "sindrets/diffview.nvim",
  requires = { "nvim-lua/plenary.nvim", "kyazdani42/nvim-web-devicons" },
  config = function()
    require("diffview").setup {}
  end,
}
```
But then when run PackerSync or PackerCompile I'm getting an error:
```
packer.nvim: Error running config for diffview.nvim: [string "..."]:0: attempt to index a boolean value
```

**Comment by sindrets** [comment]
@Nexmean plenary needs to be available on your runtime path before diffview. Add plenary as it's own packer entry early in your packer setup, or use the `after` key in diffview's packer entry to ensure it loads after plenary.

**Comment by Nexmean** [comment]
Thank you, it helped me
