### ISSUE TITLE
[feature] Go to defnition, refernce, implementation

### ISSUE THREAD

**Issue by tosiek88** [sindrets/diffview.nvim#183]
When I am doing review usually I would like to see all difference across all project files, jump into and back.
Currently in "Normal view"  I can jump into definition, reference by combination `gd`, `gr`. 

As reference I can show how it works in vscode
 
![Screenshot from 2022-07-23 07-28-05](https://user-images.githubusercontent.com/56116159/180595283-ebd654fe-bd41-4ab5-b78a-2b4b3190ceaf.png)

**Comment by sindrets** [comment]
Out of scope. These things are already implemented in LSP servers. Use the `:h diffview-actions-goto_file` mappings to open the local version of the file in a normal buffer. Then you can use LSP features like you normally would.
