### ISSUE TITLE
feature: Select lines to get related commits

### ISSUE THREAD

**Issue by matu3ba** [sindrets/diffview.nvim#187]
Video of vc with feature https://youtu.be/SQ3Beqn2CEc?t=636

I dont think coloring etc the age of changes in a file has use cases.

**Comment by sindrets** [comment]
@matu3ba This exists in the form of `:[range]DiffviewFileHistory` (or using the `-L` flag, which lets you specify multiple ranges from multiple files). From `:h :DiffviewFileHistory`:

```vimhelp
                                                *:DiffviewFileHistory*
:[range]DiffviewFileHistory [paths] [options]

                        ...


                        If [range] is given, the file history view will trace
                        the line evolution of the given range in the current
                        file (see the `-L` flag below).
```

If you select a range of lines in visual mode and press `:` the range for the visual selection will be automatically inserted into the command line.

**Comment by matu3ba** [comment]
Closed as this is already implemented.
