### ISSUE TITLE
Merge user keybindings with defaults

### ISSUE THREAD

**Issue by akinsho** [sindrets/diffview.nvim#19]
Hi 👋🏾 ,

Thanks for your work on this, I was sorely missing a way to diff things.
I just tried configuring some keybindings and was surprised to find that if I added just a single override to my keybindings setup it removes *all* default keybindings. This seems like pretty unexpected behaviour since I think most plugins will usually maintain the rest of their keybindings and just overwrite the ones you specify.

https://github.com/sindrets/diffview.nvim/blob/da19839bcdb516c780e47f554ece88ae20a77c0c/lua/diffview/config.lua#L62

This looks like it was a conscious decision though, so not sure how open you are to  it but I was thinking that you could do a merge on that line instead of either or and if a user wanted everything disabled which is the only reason I think that behaviour would be preferable maybe add a config option so users can turn off all default mappings?

anyway just though I'd raise it for discussion, despite it being easy enough to work around

**Comment by sindrets** [comment]
I'm glad you find the plugin useful!

It was indeed a conscious decision, and my rationale is this:

- It's easy to copy the provided default config, and then remove the bindings you don't want.
- It's not so easy to unmap a default binding if it conflicts with a binding you already use.

But I'm aware that this is an uncommon design rationale in the current landscape of lua plugins. So I might just do as you suggested: making the default behavior to merge bindings, and optionally do it the way it's currently done.
