### ISSUE TITLE
latest commit is bad?

### ISSUE THREAD

**Issue by mosheavni** [sindrets/diffview.nvim#192]
on commit: `c244577dd425072275eff925e87739820ac5e0aa`

I get this when opening vim:
![image](https://user-images.githubusercontent.com/17252601/185779710-400c26ce-2c32-48af-a380-a806626b6158.png)

after running `git reset --hard HEAD^` it's OK.
good commit: `a2945c82a58f23fba15c1b5319642fd6b2666df7`
Thanks.

**Comment by sindrets** [comment]
You're probably on an outdated nightly build. Some highlight attributes have been renamed in nightly. Either update your nightly build to a more recent version, or use the stable 0.7.2.

**Comment by mosheavni** [comment]
> You're probably on an outdated nightly build. Some highlight attributes have been renamed in nightly. Either update your nightly build to a more recent version, or use the stable 0.7.2.

negative. Updated to the latest nightly:
```
NVIM v0.8.0-dev+377-gae02c02f1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1654491462578.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

Still the same error.

**Comment by sindrets** [comment]
> NVIM v0.8.0-dev+377-gae02c02f1

That build is built from a commit that is three months old. Did you forget to pull?

**Comment by mosheavni** [comment]
ahh.. not sure why, I used `brew install neovim --HEAD`.
Probably didn't work

**Comment by TamaMcGlinn** [comment]
Can confirm this is still a problem. The bad commit is [this one](https://github.com/sindrets/diffview.nvim/commit/c244577dd425072275eff925e87739820ac5e0aa), suggest rolling it back.
