### ISSUE TITLE
Place cursor at the first directory

### ISSUE THREAD

**Issue by LintaoAmons** [sindrets/diffview.nvim#204]
- When enter the Diffview, the cursor was always at the last file.
- But I usually need to go to the top to stash all the changes, so is it possible to locate the cursor at the first directory?

![image](https://user-images.githubusercontent.com/95092244/188263706-a213b6a4-926f-4e10-90c2-17d2529728bf.png)

**Comment by sindrets** [comment]
It's not always at the last file in the file panel. When possible, it automatically selects the last file you were in *before* opening diffview. If you don't want this add something like `--selected-file= ` to the default args in your config (note the whitespace after the `=`).

**Comment by sindrets** [comment]
@LintaoAmons Is there anything else I should clarify, or can I close this issue?
