### ISSUE TITLE
[Bug] Diffview ignores status.showUntrackedFiles

### ISSUE THREAD

**Issue by splitDEV** [sindrets/diffview.nvim#206]
Hi, I really love your plugin, thank you for your time and effort.

For my dotfiles I use a bare repository in $HOME. When editing dotfiles I have a script which sets `GIT_DIR=$HOME` and `GIT_WORK_TREE=$HOME/.dotfiles` which gets picked up by nvim / diffview.nvim correctly.

But when opening diffview.nvim it takes ages to load (and blocks nvim while loading) due to the plugin trying to show all untracked files in my $HOME which are over 500k files.
In git I have set  `git config status.showUntrackedFiles no` to prevent a git diff/status showing all files.
I'm aware I could call `:DiffViewopen -uno` to prevent showing all untracked files (which works), but it would be great if diffview.nvim would pickup `status.showUntrackedFiles` from the git environment automatically.

Actually I debugged your code and found out that the function `show_untracked(..)` in `lua/diffview/git/utils.lua` returns true when opening the diffview (as the call to `exec_sync(..)` returns with an 128 error and `out` being nil). If I just `return false` from the function it works as I would expect.

If I change the function like so, everything works for me:
```
function M.show_untracked(toplevel)
    local out = M.exec_sync(
        { "config", "status.showUntrackedFiles" },
        { cwd = toplevel, silent = true }
    )
    return vim.trim(out[1] or "") ~= "no"
end
```
Maybe this helps?

**Comment by sindrets** [comment]
@splitDEV exit code 128 is a fatal application error in git. I would not expect to see that in this scenario even if you hadn't defined `status.showUntrackedFiles`. What git version are you using? Could you perhaps show the git config for your dotfiles repo?

I use a very similar setup for my own dotfiles and I don't have this problem.

**Comment by splitDEV** [comment]
Thank you for your reply and sure, here are some logs

![image](https://user-images.githubusercontent.com/7757191/188895800-d9860f39-0a13-42d9-9fbf-172390c2be97.png)

And here are the showUntrackedFiles entries:

![image](https://user-images.githubusercontent.com/7757191/188896899-96895e8c-9838-4f83-bd6b-ebdc426d7601.png)

According to `man git-config` or https://git-scm.com/docs/git-config `status.showUntrackedFiles` isn't a bool flag. Your code tries to map `all` to bool which fails.

I hope this helps?

**Comment by sindrets** [comment]
I know it's not a boolean flag, but I thought that `--type=bool` would canonicalize it as such. And I thought I had tested that, but clearly I'm wrong.

Thank you for the bug report, I'll fix this as soon as I have some time.

**Comment by splitDEV** [comment]
No problem, I'm glad to help.

If my posted solution is ok, I can later create a PR if you like.

**Comment by sindrets** [comment]
Your solution seems correct, and PRs are always welcome :)
