### ISSUE TITLE
[Feature] Marking base commit

### ISSUE THREAD

**Issue by MikePresman** [sindrets/diffview.nvim#210]
diffview.nvim is awesome thanks for working so hard on it. The merge tool is what got me excited on it and I'm loving it even more as I learn more about it.

I do have one feature request, curious if it's feasible. Altneratively to `:DiffviewFileHistory --base=<commit>`, Would it be possible to bind keys like "b" to set specific commits as the base while the file history buffer is open so I can interactively move the base around? 

This would simplify having to do `:DiffviewFileHistory --base=<commit>` in the sense that I would not have to remember a specific hash I'd like to set as the base and having to rexecute the command each time.

Thank you !

**Comment by sindrets** [comment]
> diffview.nvim is awesome thanks for working so hard on it. The merge tool is what got me excited on it and I'm loving it even more as I learn more about it.

I'm very glad to hear that, thank you so much!

---

Yes, I think both the `--base` flag and path arguments should be exposed and configurable through the option panel. It's kinda strange that I haven't put it there yet actually.

In terms of creating a more accessible keymap: it's possible to add recursive mappings that first open the option panel and then trigger one of the option flags. Example for the `++rev-range` option:

```lua
require("diffview").setup({
  keymaps = {
    file_history_panel = {
      ["g!"] = actions.options,
      { "n", "r", "g!=r", { remap = true } }, -- Press `r` to change the `++rev-range`
    },
  },
})
```

**Comment by MikePresman** [comment]
I'm glad you agree and hopefully you yourself could find it to be useful for your day to day.

In terms of the file_history_panel key-mappings to rev-range thank you, you just opened a new exciting realm for me I was unaware of :eyes: :partying_face: 

Thanks again, I hope you have time to implement the `--base` flag and path args as configurable; and if not, thanks for your consideration and time in any case.

**Comment by sindrets** [comment]
Implemented in the latest commit :)
