### ISSUE TITLE
Cannot move cursor to next or prev modify

### ISSUE THREAD

**Issue by tanathap** [sindrets/diffview.nvim#211]
I'm not sure if I did anything wrong or it's just not support. But I cannot move between modify by press "[" + "x" or "]" +"x", when I type [x nothing happen. but I actually need it because I have many modify in 1 file so it's will helpful if i can move. or if anyone know how to, pls tell me.

**Comment by sindrets** [comment]
`[x` and `]x` are only for jumping between merge conflict markers. Use `[c` and `]c` to jump between diff hunks.
