### ISSUE TITLE
DiffviewOpen and then DiffviewClose 'close' error

### ISSUE THREAD

**Issue by natdm** [sindrets/diffview.nvim#213]
![Screen Shot 2022-09-13 at 7 58 24 AM](https://user-images.githubusercontent.com/11272201/189936183-399e5694-b602-4f68-aa14-88e2020b197b.png)

All I do is run DiffviewOpen then DiffviewClose. 

The error here is shown, and if I exit that, I have a tab left over with `d//null` as the title. Trying to close that yields the below error (but does close the window)
![Screen Shot 2022-09-13 at 8 00 34 AM](https://user-images.githubusercontent.com/11272201/189936402-f8013235-b02b-4925-9229-861e9897ebd7.png)

After the first errors, and after exiting them all, running DiffviewOpen in a project yields the below:
![Screen Shot 2022-09-13 at 8 01 14 AM](https://user-images.githubusercontent.com/11272201/189936545-163274be-571c-4a3c-bb54-be4d33aadeb8.png)

Love the plugin but I have to exit neovim every time I use it.

**Comment by sindrets** [comment]
I'm gonna need a minimal config and reproduction steps that makes this reproducible. This seems related to your config. [Here's a template](https://gist.github.com/sindrets/3e671e79ce4566667f9ec176786dfadd).

> E445: Other window contains changes

Do you not have `'hidden'` enabled?

In the two last stack traces you provided, `shade.nvim` seems to be involved. I'm not sure whether or not it is actually involved in producing the first error, but it's at least something for you to investigate.

**Comment by natdm** [comment]
Welp, it was indeed Shade. That's the second time it's happened, sorry to lead you astray. Just going to delete shade for now. Thank you for your help!

For the record, no idea what you mean by `hidden`. I've looked in the readme and help but don't see any reference.

**Comment by sindrets** [comment]
No worries, glad you figured it out.

> For the record, no idea what you mean by `hidden`. I've looked in the readme and help but don't see any reference.

It's a (n)vim option. See `:h 'hidden'`. In nvim it's enabled by default. When it's disabled, all buffers are immediately deleted when they are no longer displayed in a window. To my knowledge `E445` can only occur when `'hidden'` is disabled or you have a buffer with `bufhidden=wipe` or `bufhidden=delete`. Maybe `shade.nvim` is using the latter.
