### ISSUE TITLE
How to get the bufnr of file_panel?

### ISSUE THREAD

**Issue by adrian-soomro** [sindrets/diffview.nvim#217]
Hi, 

I'd like to preface this by saying that I'm quite new to NeoVim.

I've setup your plugin in no time and its amazing, thank you for making it. 

I'd like to document the keymappings that are scoped to individual buffers (merge_tool, file_panel, etc) with the help of [which-key](https://github.com/folke/which-key.nvim). The whichkey plugin can do that if you pass it a buffer number. 

I've played around with it a bit and I can see that every section of the diffview has different buffer number. I was hoping I could listen for an event that happens when the buffers are opened (using the hooks config), get the bufnr from there and set up my which-key keybindings, however, I can't find a way to do that.

The question is - would you know how can I get the buffer number of the file_panel?

**Comment by sindrets** [comment]
> I've setup your plugin in no time and its amazing, thank you for making it.

Glad to hear that, thank you!

---

`BufWinEnter` should probably do the trick:

```lua
vim.api.nvim_create_autocmd("BufWinEnter", {
  pattern = "DiffviewFilePanel",
  callback = function(ctx)
    print("bufnr:", ctx.buf)
  end,
})
```

**Comment by adrian-soomro** [comment]
That's exactly what I was looking for!
Thank you.

![image](https://user-images.githubusercontent.com/37105695/190866775-99d8fa62-8858-417f-89ee-bd11275c6050.png)
