### ISSUE TITLE
bug: `wildcard` expansion is not handled correctly

### ISSUE THREAD

**Issue by younger-1** [sindrets/diffview.nvim#218]
From `:h :DiffviewFileHistory`:

> Multiple [paths] may be provided and git pathspec is supported (see :Man gitglossary(7) for information about pathspec).

When I typed `:DiffviewFileHistory lua/young/key/normal/leader.lua lua/young/key/visual/leader.lua`, I could diffview those two files.
But when I typed `:DiffviewFileHistory lua/**/leader.lua`, it shows:

```
[Diffview.nvim] No git history for the target(s) given the current options! Targets: 'lua/young/key/normal/leader.lua
lua/young/key/visual/leader.lua'
Current options: [ Top-level path: '~/.config/nvim', Flags: '--diff-merges=combined' ]
```

Looks like `DiffviewFileHistory` do not support this kind of git pathspec

**Comment by sindrets** [comment]
@younger-1 The problem is that nvim will expand that pattern before it gets to git. And nvim's expansion contains newlines that are currently not handled. Use a colon before the path to indicate that it should be interpreted as pathspec: `:lua/**/leader.lua`.

**Comment by sindrets** [comment]
Wildcard patterns are now handled correctly in the latest commit. But do keep in mind that if you don't prepend a colon before the path, or escape the asterisks (*) with a backslash, then nvim will handle the path expansion. Not git. For these glob patterns I'm assuming it won't matter most of the time. But it's worth keeping in mind.

Just to be clear:

```vim
" Expanded by vim:
:DiffviewFileHistory foo/bar/*
:DiffviewFileHistory foo/bar/*.baz
:DiffviewFileHistory foo/**/baz

" Expanded by git:
:DiffviewFileHistory foo/bar/\*
:DiffviewFileHistory :foo/bar/*.baz
:DiffviewFileHistory :(glob)foo/**/baz
```

**Comment by younger-1** [comment]
Sooo quickly! Thanks for your awesome work!
