### ISSUE TITLE
Recent commit breaks DiffviewFileHistory --range argument handling

### ISSUE THREAD

**Issue by adizero** [sindrets/diffview.nvim#219]
Recent commit has broken DiffviewFileHistory --range argument handling:

:DiffviewFileHistory --range=origin..HEAD
[Diffview.nvim] Bad revision: "origin..HEAD"

Caused by this commit:

commit b31fafb71f35e4f2a4bd95481ff7d59b1caae387 (HEAD)
Author: Sindre T. Strøm <sindrets@gmail.com>
Date:   Tue Sep 13 22:49:33 2022 +0200

    feat(file-history): Expose `++base` and path args in the option panel.
    
    Both the `++base` and the path args can now be configured from within a
    file history view, as these options have now been exposed in the option
    panel.
    
    (resolves #210)

**Comment by sindrets** [comment]
Thanks for the report! Fixed in the latest commit.
