### ISSUE TITLE
feature: allow `--follow` to handle **multiple file**

### ISSUE THREAD

**Issue by younger-1** [sindrets/diffview.nvim#220]
This is useful when browsing multiple related files.

```vim
" Multiple path
DiffviewFileHistory --follow a b
DiffviewFileHistory --follow foo**bar
```

From the docs, i know that `--follow` is only for single file which is correspond to `git log --follow`.
I don't if this feature is reasonable/possible, so close the issue casually at your will

**Comment by sindrets** [comment]
Sorry, it's not supported by git. You should look for an issue upstream.

In some situations you can somewhat get around this by using glob patterns. Say you know that multiple files called `bar` might have been moved around in sub-directories of `foo`, you can do:

```
:DiffviewFileHistory :foo/**/bar
```

If the file could have been renamed as well, it's a bit worse. But again if you have some knowledge about the nature of the change, you can probably find it using patterns. I.e. you know that `bar` might have previously gone under the name `qux`:

```
:DiffviewFileHistory :foo/**/bar :foo/**/qux
```

**Comment by younger-1** [comment]
The workaround looks good to me! I had thought how to combine each result of `git log --follow` after expanding wildcard, since it's the only way I could come up with when upstream git remain unchanged. Thanks you all the same!
