### ISSUE TITLE
[feature] allow edits in right window

### ISSUE THREAD

**Issue by steve-lorimer** [sindrets/diffview.nvim#221]
Often when viewing a diff I want to make small changes to the file

eg: 

- I'm viewing a diff, and a mistaken keypress which added a stray character jumps out as it's highlighted in the diff
- I spot a small typo and want to fix it while reviewing the diffs

Being able the make these changes while in diff mode will be really useful.

**Comment by sindrets** [comment]
The diff buffer in the right window *is* editable when the window is displaying the local version of the file. What arguments are you passing to `:DiffviewOpen`?

**Comment by steve-lorimer** [comment]
Ah man - sorry! :facepalm: I just tried again and it works! I guess I must have been focused in the left window without realising!

Is there an option to "close as not planned - user is an idiot!"?

**Comment by sindrets** [comment]
Happens to the best of us, glad you figured it out! :)

**Comment by simonmandlik** [comment]
@sindrets is diffview.nvim supposed to make non-local files nonmodifiable? :)

When I call `:DiffviewOpen` all buffers, including index files are modifiable. I am using this the following to achieve this:

```lua
hooks = {
    diff_buf_read = function()
        -- make "diff" buffers non-modifiable
        local fname = vim.fn.expand('%:h')
        if fname:match("diffview") or fname:match("gitsigns") then
            vim.opt_local.modifiable = false
        end
    end
}
```
