### ISSUE TITLE
Bug: Layout fails with `E36: Not enough room` when using `noequalalways`

### ISSUE THREAD

**Issue by AlanWarren** [sindrets/diffview.nvim#222]
Hello, thanks for the excellent plugin. 

I wanted to test out the new merge capabilities, and finally had a conflict arise to test it out with today.  When using `:DiffviewOpen` from the conflicted file, I'm seeing the following errors.
```
Error executing vim.schedule lua callback: ...ig/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: .../diffview.nvim/lua/diffview/sce
ne/layouts/diff_3_hor.lua:43: Error executing lua: .../diffview.nvim/lua/diffview/scene/layouts/diff_3_hor.lua:44: Vim(vsplit):E36: Not enough room
stack traceback:
        [C]: in function 'cmd'
        .../diffview.nvim/lua/diffview/scene/layouts/diff_3_hor.lua:44: in function <.../diffview.nvim/lua/diffview/scene/layouts/diff_3_hor.lua:43>
        [C]: in function 'resume'
        ...ig/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:45: in function <...ig/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:44>
stack traceback:
        [C]: in function 'error'
        ...ig/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
        ...ig/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:45: in function <...ig/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:44>
```

I'm using the default configuration, with the exception of `enhanced_diff_hl = true`. 
```lua
require("diffview").setup({
  enhanced_diff_hl = true, -- See ':h diffview-config-enhanced_diff_hl'
})
```
I've tried different merge_tool layout's but it's the same error every time.  I have diffview.nvim updated to https://github.com/sindrets/diffview.nvim/commit/5d3d11aad8deaaa3fec1968a2707846cfd12918a but I've also tried stepping through previous commits.  The only point in history where this issue does not occur is https://github.com/sindrets/diffview.nvim/commit/e32de2be00e0b5e23736f906f3d6d9dca14fbeb0

I notice it says "Not enough room" but not sure what it's referring to.  Dismissing the error results in two file explorer windows adjacent to each other, along with what appears to be 2 more collapsed file explorers, along with the 2 split views I normally see. 
![image](https://user-images.githubusercontent.com/294606/191061720-e4f81483-c275-4e0f-ab4f-4ef9b9646ee1.png)

Version: `NVIM v0.8.0-dev-1093-g982fef601`

thanks

**Comment by sindrets** [comment]
> Vim(vsplit):E36: Not enough room

That's a very strange error. I can't reproduce this with my own config, nor with a minimal config. Even when testing with a really small editor window. It's highly likely that something in your config - either an auto command, or a plugin - is interfering with the layout creation.

I'm gonna need you to provide a minimal config that makes this issue reproducible. [Here's a template](https://gist.github.com/sindrets/3e671e79ce4566667f9ec176786dfadd).

**Comment by AlanWarren** [comment]
> > Vim(vsplit):E36: Not enough room
> 
> That's a very strange error. I can't reproduce this with my own config, nor with a minimal config. Even when testing with a really small editor window. It's highly likely that something in your config - either an auto command, or a plugin - is interfering with the layout creation.
> 
> I'm gonna need you to provide a minimal config that makes this issue reproducible. [Here's a template](https://gist.github.com/sindrets/3e671e79ce4566667f9ec176786dfadd).

Thanks, I was able to track it down.  I have `set noea` in my init, which is responsible for the bug in question.  Removing this from my config resolves the problem. I do prefer my splits to stay fixed size, but it's not a big deal.

**Comment by sindrets** [comment]
Interesting. Having `noequalalways` causes the splits produced by the layout to be either 1 column wide, or 1 row tall. I never would have thought to check that option so I'm glad you found the cause.

I suppose the simplest way to handle this is to temporarily enable `equalalways` during layout creation.
