### ISSUE TITLE
Diff selected with clipboard

### ISSUE THREAD

**Issue by LintaoAmons** [sindrets/diffview.nvim#224]
I missing this function from IDEA, and found there's already codes to achieve this

But maybe Diffview could add this into it's toolbox.

from: https://www.reddit.com/r/neovim/comments/sg919r/diff_with_clipboard/

```lua
function _G.compare_to_clipboard()
	local ftype = vim.api.nvim_eval("&filetype")
	vim.cmd("vsplit")
	vim.cmd("enew")
	vim.cmd("normal! P")
	vim.cmd("setlocal buftype=nowrite")
	vim.cmd("set filetype="..ftype)
	vim.cmd("diffthis")
	vim.cmd([[execute "normal! \<C-w>h"]])
	vim.cmd("diffthis")
end
```

**Comment by sindrets** [comment]
It's too specific and easily worked around with a small function like you've suggested.

Someone recently asked for a register based diff, and I provided a [custom user command for that in this thread](https://github.com/sindrets/diffview.nvim/issues/215#issuecomment-1250070954). This can also diff the clipboard of course, with either the `*` or the `+` register. Between that snippet and the snippet suggested in your OP I think your requested functionality is covered.
