### ISSUE TITLE
use_icons = false still displays spaces used to separate icons in file panel

### ISSUE THREAD

**Issue by charbelnicolas** [sindrets/diffview.nvim#227]
When using the option use_icons = false, the file panel will display an extra space in between the file status and the file name.

![space](https://user-images.githubusercontent.com/14960414/193578485-1a2342fb-c426-491f-8a05-ddff4e104802.png)

After editing the diff/render.lua:

![20221003_074120](https://user-images.githubusercontent.com/14960414/193579162-0ba18259-e7ae-44d8-96fd-379c8e394515.png)

Video showing the difference:

https://user-images.githubusercontent.com/14960414/193579913-13705b12-9508-4a18-8b7d-c0d697b17950.mp4

This probably happens in other places where icons are used too, I haven't checked everything.

**Comment by sindrets** [comment]
@charbelnicolas Seems like you've fixed this yourself locally. Please submit a PR, and then I can take a closer look.

**Comment by charbelnicolas** [comment]
https://github.com/sindrets/diffview.nvim/pull/229

**Comment by charbelnicolas** [comment]
BTW, is there a way to remove the left padding on the file panel?

**Comment by charbelnicolas** [comment]
> BTW, is there a way to remove the left padding on the file panel?

NVM, I found the related code under the Panel.winopts on the panel.lua file. Is there a reason `signcolumn` has to be set to `"yes"`? I've changed it to `"auto"` and it removes the padding but I'm not sure if the sign column is needed for anything else...

**Comment by sindrets** [comment]
I'm using the sign column as a margin in the interface. It's purely aesthetic. If you don't like it you can disable it in your config with `file_panel.win_config.win_opts.signcolumn = "no"`.

**Comment by charbelnicolas** [comment]
> I'm using the sign column as a margin in the interface. It's purely aesthetic. If you don't like it you can disable it in your config with `file_panel.win_config.win_opts.signcolumn = "no"`.

Hello Sindre, is there a way to access these in the config options?

![20221005_214439](https://user-images.githubusercontent.com/14960414/194359369-54af1eb9-808b-4cc5-bb8d-c006c49acf2a.png)

I want to remove the foldcolumn completely otherwise the text shifts when going from the normal buffer to the diffview.

**Comment by sindrets** [comment]
@charbelnicolas Sorry, I missed the notification for this reply. To change local options in diff buffers you should use the provided hooks / auto commands. Please see `:h diffview-config-hooks`. There are examples there on how to use `diff_buf_read` to set local options.

**Comment by charbelnicolas** [comment]
> @charbelnicolas Sorry, I missed the notification for this reply. To change local options in diff buffers you should use the provided hooks / auto commands. Please see `:h diffview-config-hooks`. There are examples there on how to use `diff_buf_read` to set local options.

Alright, thank you!
