### ISSUE TITLE
[question/feature] customize 'gf'

### ISSUE THREAD

**Issue by emmanueltouzery** [sindrets/diffview.nvim#230]
Hello, I'd like to customize `gf` from diffview. Neither `gf` nor `<c-w>gf` exactly fit what i'd like.
I'd like to close diffview's tab, so return to the main tab, then invoke https://github.com/t9md/vim-choosewin to decide in which window to open the file.
To achieve that, I'd need somehow to get from diffview the information of which file is currently displayed in diffview, either through some API function call, or maybe through a hook that diffview would call with the filename whenever the user selects a file in diffview (i would then store the filename in a global variable that my shortcut could read when i invoke it).

Is that possible today with diffview's API? Thank you!

**Comment by sindrets** [comment]
@emmanueltouzery You can get the absolute path to the local version of the current file like this:

```lua
local file = require("diffview.lib").get_current_view():infer_cur_file()
if file then
  print(file.absolute_path)
end
```

Although, this uses the undocumented internal plugin API. I offer no promises of stability for this API. However, it hasn't changed in a long time, and I have no plans to change it at the moment, so you'll probably be fine using this, as long as you're aware that there's a possibility that it could change at some point in the future.

**Comment by sindrets** [comment]
If you want / need a stable public API you can open a new issue where we can discuss this.

**Comment by emmanueltouzery** [comment]
thank you, this works great! I'm ok using this api for now and if it breaks down the line we can maybe talk about it again. whether it's worth making a public api, i guess you'll see whether there's only one person asking for it or maybe more, i guess.

thank you again and.. again... this plugin is really awesome, much much appreciated. a really pillar of my git workflow. :heart:
