### ISSUE TITLE
Question: how can I display the full content of a selected file in DiffviewFileHistory? 

### ISSUE THREAD

**Issue by nadeemkhedr** [sindrets/diffview.nvim#234]
Hello!

When doing `:DiffviewFileHistory %` on a file, the file opens diff mode with older commits that affected that file.
I want to be able to view the full file of a previous commit instead of a diff view. Is that possible?

**Comment by sindrets** [comment]
As in opening the folds? Just press `zR` in either of the diff buffers. See `:h fold-commands`.

**Comment by nadeemkhedr** [comment]
So cool! I didn't know that diffview was using folds to hide the rest of the information
