### ISSUE TITLE
Add support for yadm

### ISSUE THREAD

**Issue by ananthhh** [sindrets/diffview.nvim#237]
I am currently managing my dotfiles along with neovim config with https://yadm.io/
It will be great if diffview supports YADM.

**Comment by sindrets** [comment]
I'm not familiar with YADM, so you're gonna have to elaborate. YADM uses git doesn't it, so what exactly is the issue? Please be more specific about what you mean by "diffview support for YADM".

**Comment by ananthhh** [comment]
Yes. YADM uses git. I am not sure how it works internally. I will do a bit of research and get back with more specific details. 
I will try to fix this myself and send a PR if that's alright.

Thanks!

**Comment by sindrets** [comment]
I suspect you probably just need to let git know where YADM's git dir is, and explicitly set the work tree. From a quick google search it seems like the default location for the YADM git dir is `$HOME/.local/share/yadm/repo.git`. So if you do something like this, it should work:

```
:lua vim.env.GIT_DIR = vim.fn.expand("~/.local/share/yadm/repo.git"); vim.env.GIT_WORK_TREE = vim.fn.expand("~")
```

**Comment by ananthhh** [comment]
Thanks for the hint @sindrets
It works. It's a bit of a hassle to update GIT_DIR whenever I change project. But can be easily solved with autocmd I believe.

**Comment by sindrets** [comment]
There's currently a big refactor in the works by @zegervdv (#235) that will - among other things - make it simple to implement a way to explicitly set both the `GIT_DIR` and the `GIT_WORK_TREE` path for individual views. That way you will be able to do something like:

```
:DiffviewOpen --git-dir=~/.local/share/yadm/repo.git --work-tree=~
```

without having to fiddle with environment variables. And this won't affect other views.

I'll see if I can take a look at this after we have merged the refactor.

**Comment by hermitmaster** [comment]
> Thanks for the hint @sindrets
> It works. It's a bit of a hassle to update GIT_DIR whenever I change project. But can be easily solved with autocmd I believe.

Use [direnv](https://direnv.net). It manages your environment based on CWD.

**Comment by ananthhh** [comment]
> Use [direnv](https://direnv.net). It manages your environment based on CWD.
Yeah. But having .envrc on home folder is not optimal. direnv look for .envrc in parent folders and I will be forced to have .envrc in all my projects.

**Comment by ananthhh** [comment]
> There's currently a big refactor in the works by @zegervdv (#235) that will - among other things - make it simple to implement a way to explicitly set both the `GIT_DIR` and the `GIT_WORK_TREE` path for individual views. That way you will be able to do something like:
> 
> ```
> :DiffviewOpen --git-dir=~/.local/share/yadm/repo.git --work-tree=~
> ```
> 
> without having to fiddle with environment variables. And this won't affect other views.
> 
> I'll see if I can take a look at this after we have merged the refactor.

That would solve the problem. I can just create a keybinding for this command
