### ISSUE TITLE
Suggestion: Use desc for keymap, and/or add help menu

### ISSUE THREAD

**Issue by wookayin** [sindrets/diffview.nvim#239]
I often forget what are the available keymaps in the filetree panel and the diffview panel.

Looking at help or README (go out of way to open a web brwoser!), or config files would help, but it's quite bothersome.
```
:h diffview-config-keymaps
:h diffview-actions
```

**Suggestion**: Can we add some nice help menu? (in the floating window)

For example, neo-tree.nvim has a very nice help menu when user presses `?` in the window:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/1009873/198868297-fce3d25e-9ce8-4cb1-8439-de86eb9c3d5e.png">

Or as a vimmer, I would try `:map <buffer>` (or `:verbose map <buffer>`) to see all the available buffer-local keymaps, but lua configs are quite difficult to interpret:

```
n  <Tab>       *@<Lua 7010: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>  
n  <CR>        *@<Lua 6969: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>  
x  "            @peekaboo#peek(v:count1, '"',  1)                                       
n  "            @peekaboo#peek(v:count1, '"',  0)                                       
n  ,e          *@<Lua 2666: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>  
n  ,b          *@<Lua 5846: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>  
n  -           *@<Lua 7249: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>  
n  @            @peekaboo#peek(v:count1, '@', 0)                                        
n  L           *@<Lua 447: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>   
n  R           *@<Lua 425: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>   
n  S           *@<Lua 6995: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>  
n  U           *@<Lua 5580: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>  
n  X           *@<Lua 7066: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>  
n  [x          *@<Lua 6998: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:191>  
n  ]x          *@<Lua 6996: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:160>  
n  f           *@<Lua 7218: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>  
n  g<C-X>      *@<Lua 2405: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:403>  
n  gf          *@<Lua 416: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:67>    
n  i           *@<Lua 6997: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>  
n  j           *@<Lua 7011: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>  
n  k           *@<Lua 7839: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>  
n  o           *@<Lua 7013: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>  
n  <C-W>gÞ     *@<Nop>                                                                  
n  <Up>        *@<Lua 7205: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>  
n  <C-W><C-F>  *@<Lua 6999: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:121>  
n  <2-LeftMouse> *@<Lua 5348: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>
n  <C-W>gf     *@<Lua 5593: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:140>  
n  <Down>      *@<Lua 424: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>   
n  <C-B>       *@<Lua 2386: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:266>  
n  <S-Tab>     *@<Lua 5985: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:494>  
n  <C-F>       *@<Lua 7024: ~/.vim/plugged/diffview.nvim/lua/diffview/actions.lua:266>  
```

This could be improved if we add ` { desc = ... }` (description) option to `vim.keymap.set(...)`.

**Comment by sindrets** [comment]
I sympathize with your frustration and I'm in favor of having a popup for showing keymaps (this is already being tracked in #168). However, I simply don't have the motivation, nor time to focus on this right now. 

PR's updating / adding documentation or an implementation of a help-popup, are very welcome :)

---

> Looking at help or README (go out of way to open a web brwoser!), or config files would help, but it's quite bothersome.

The help document contains all the information from the README, as well as a lot more. You should never *need* to open the README in a browser. You mentioned some help tags, but I want to also add `:h diffview.defaults`. This is a document that contains all the default options, including keymaps, accompanied by a short comment describing what they do.

As I suggested in the linked issue, you could add a keymap for opening this document (and if you use the verbose way of declaring keymaps, you can also add the `desc` data yourself):

```lua
require("diffview").setup({
  keymaps = {
    file_panel = {
      { { "n" }, "g?", "<Cmd>h diffview.defaults<CR>", { desc = "Open the default config" } },
    },
  },
})
```

**Comment by wookayin** [comment]
c6c51ab2d7d9ab8eaf7bfd8794bedd10f9fad2e6 seems an (unexpected) breaking change.

**Comment by sindrets** [comment]
It _seems_ like a breaking change? How so?
