### ISSUE TITLE
FR: Support for git pickaxe for `:DiffviewFileHistory`

### ISSUE THREAD

**Issue by chrisgrieser** [sindrets/diffview.nvim#244]
As far as I can tell, the `:DiffviewFileHistory` allows to dynamically search for an author name or the content of a commit message, but not for changes i.e., [git pickaxe](http://www.philandstuff.com/2014/02/09/git-pickaxe.html) ([git docs for `git log -[SG]`](https://git-scm.com/docs/git-log#Documentation/git-log.txt--Sltstringgt))

Going through the docs, the only way to use the `-G` and `-S` options seems to be the `default_args` or `log_options` config, which would define those statically, instead of being able to dynamically search for a string.

**Comment by sindrets** [comment]
Yes, I've been meaning to add this for a while, but I haven't had much time to work on the plugin lately.

You can't add `-[SG]` to `default_args`. The `default_args` entries only accepts the same options as their respective commands. See `:h :DiffviewOpen` and `:h :DiffviewFileHistory` for the overview of the available options.

**Comment by chrisgrieser** [comment]
thanks so much 🥳
