### ISSUE TITLE
`DiffviewFileHistory` commit messages display options

### ISSUE THREAD

**Issue by aborzunov** [sindrets/diffview.nvim#245]
Is it possible to:
1. customise maximum commit length in `:DiffviewFileHistory`, so they were not truncated.
2. display full commit message

Thank you!

**Comment by sindrets** [comment]
You can't customize the max commit message length, but you can show the full commit details in a floating window by moving the cursor to a commit and pressing `L`.

**Comment by aborzunov** [comment]
Thank you for your answer, `L` works perfectly, though having option for commit length would be a nice feature.
