### ISSUE TITLE
How to grep the git revision out of an URI

### ISSUE THREAD

**Issue by tummetott** [sindrets/diffview.nvim#251]
Hello, 

When I'm in a diffsplit, I want my statsuline+winbar plugin (feline.nvim) to show the filename and git revison of the temporary buffer in my winbar. Diffview.nvim uses a URI as filename for the temporary buffer which is fine, but I don't want to show that ugly string in the winbar. Now I'm struggeling to extract the git revision out of that string.
When I was using fugitive, an example URI looked like this:

```"fugitive:///Users/jonas/.dotfiles/.git/modules/configs/nvim//86ee9f9b2461194d745c93ec3e6d211412560e23/lua/tummetott/plugins/feline.lua"```

The important part is the double slash before the git revision (the git commit)

Because of the double slash, I could easily parse the URI with the following code:
```lua
local filename = vim.api.nvim_buf_get_name(0)
if vim.startswith(filename, 'fugitive://') then
    _, _, gitpath, innerpath, revision, relpath = filename:find('fugitive://(.*)%.git/modules/(.*/)/([^/]+)/(.*)')
end
```

Diffview does not have such a regex anchor like the double slash.

Diffview changed it's URI layout not long ago if i'm not mistaken. In my old config, I could grep the revison with:
```lua
if vim.startswith(filename, 'diffview://') then
    _, _, gitpath, revision, relpath = filename:find('diffview://(.*)%.git/([^/]+)/(.*)')
end
```

Before the update, the `.git` directory served as anchor to grep the git revision.

So my question: am I missing something, how I could parse the URI or is this just not possible after the URI layout change?
If so, would it be possible to put a regex anchor in the URI string, e.g. the double slash like fugitive did it?

Thank you in advance

**Comment by Tummetott** [comment]
If I would know the original filename of the file I diff against, I could also solve the problem I guess. But I also don't see a way how to obtain that original filename

**Comment by sindrets** [comment]
You could do this:

```lua
local bufname = vim.api.nvim_buf_get_name(0)
local git_dir = require("diffview.lib").get_current_view().adapter.ctx.dir
local rev = bufname:match(("^diffview://%s/(.-)/"):format(vim.pesc(git_dir)))
```

The buffer names have not changed in any meaningful way for a long time as far as I can remember. The structure of the URI's is:

```
diffview://{git_dir}/{rev}/{path}
```

Where the variables represent the following:

- `git_dir`: Path to the git dir (typicaly the `.git` dir. But not necessarily)
- `rev`: The abbreviated revision object name. Will either be an abbreviated commit SHA, or a stage number `:[0-3]:`.
- `path`: The path to the file from the top-level of the repo.

Fugitive also uses the path to the git dir as the first component of its URI's, so it's not reliable to match against `.git` in the buffer name. I.e. git worktrees will typically have their git dirs outside of the repo. Further, any repo can configure the git dir to be anywhere on the file system.

**Comment by Tummetott** [comment]
Oh wow thank you. I did not know about this function:
```lua
require("diffview.lib").get_current_view().adapter.ctx.dir
```
That solves the problem perfectly 💯

Since you're such an expert here, can I ask you another thing?
Is there another internal diffview function I could call to get the abbreviated commit SHA of HEAD? Or does neovim's buildin diff library have such a function?

**Comment by sindrets** [comment]
The simple way to do that without relying on diffview would be:

```lua
local rev = vim.trim(vim.fn.system({
  "git", "rev-parse", "--revs-only", "--short", "HEAD"
}))
```

But that won't necessarily give you the HEAD for the repo in the current diffview. If you want that, then you could do:

```lua
local view = require("diffview.lib").get_current_view()
if view then
  local rev = view.adapter:exec_sync({ "rev-parse", "--revs-only", "--short", "HEAD" })[1]
end
```

> Or does neovim's buildin diff library has such a function?

No. (N)vim's diff mode has nothing to do with git. It's a general diff tool that can diff any two to eight buffers, or - through the API - any two given sets of text.

**Comment by Tummetott** [comment]
Thank you all problems solved 🔝

**Comment by sindrets** [comment]
Discussion was continued in #433.
