### ISSUE TITLE
Layouts not working

### ISSUE THREAD

**Issue by goschevski** [sindrets/diffview.nvim#252]
Hi,

I'm maybe doing something wrong, but I can't switch to any layout except for diff2_vertical and diff2_horizontal.
When I try to override config, it show's an error that only those 2 are available. I also tried cycling via g<C-x> but it cycles just those 2?

Great plugin though, good job!

**Comment by gegoune** [comment]
Make sure you are changing correct `x` key in `view` table, there are three of four different ones, have a look at `:h diffview-config-view.x.layout` to see which layouts are available for which views.

**Comment by goschevski** [comment]
Ah, thanks. I read that, but not everything. :)

Is it possible to implement new layout where you would see everything in one column? Something like this:

<img width="416" alt="Screenshot 2022-11-17 at 20 54 15" src="https://user-images.githubusercontent.com/1169329/202545723-c338c44b-e863-4fbb-9a99-c41bc1e4ad4b.png">

**Comment by sindrets** [comment]
@goschevski That's an inline diff. This plugin uses the strengths of (n)vim's builtin diff mode. The builtin diff mode does not support this, and thus it is not supported here.

Inline diffing is already being tracked as a feature request in #39. However, I'm not prioritizing it. See that thread for some alternatives.

Closing in favor of the mentioned thread.
