### ISSUE TITLE
Is it possible to use the git merge tools on marked-up files (i.e., files that contain `<<<`, `===`, and `>>>`) outside a git repo?

### ISSUE THREAD

**Issue by aalbaali** [sindrets/diffview.nvim#256]
I wrote up this question on [Stackoverflow](https://stackoverflow.com/questions/74538999/is-it-possible-to-use-the-git-merge-tools-on-files-that-contain-conflict-markers) hoping for a generic answer, but now I'm wondering if there's a diffview-specific solution that might solve the issue.

Thanks

**Comment by sindrets** [comment]
Like people explained in your SO question, during a merge or rebase git provides the set of conflicted files as well as all the different versions of a conflicted file from the index. Similarly to all git-mergetools I'm aware of, Diffview relies on these mechanics.

Just to mention some solutions that might work that weren't mentioned in your SO post:

- Perhaps you could make a script that stores the conflicted version of the files in Git's object database by using `git-mktree` or `git-hash-object`. Then you can solve the conflict any way you want, and then use some rebase magic to create a commit out of the tree you stored, and include it in your branch.

Just an idea.

**Comment by aalbaali** [comment]
I'll give those tools a try. Thanks for your feedback.
