### ISSUE TITLE
The new help pane does not show a description for all the keymaps

### ISSUE THREAD

**Issue by danielo515** [sindrets/diffview.nvim#263]
Hello.
The latest addition of a help pane is a super QOL improvement.
I just updated to 6a82dfc and tested it.
It works as expected, but some keymaps, rather than showing the description are showing a reference to the lua function they will call. Take a look at the following screenshot:

![image](https://user-images.githubusercontent.com/2270425/204997957-ec0ca220-d8e5-4185-b9b6-150640e13f3e.png)

If you accept an additional suggestion, I think it will be awesome to show a little hint about how to open the help window. It may not be obvious for everyone, and it will be easier that way to make it fulfil its purpose.
Also, as a nice touch, if the h and j keys were jumping directly to the next entry will be awesome. There is no reason to be able to put the cursor in the firs 5 lines

**Comment by sindrets** [comment]
You have to define the `desc` field for the keymaps that you want to have described. This is now done by default, so you have probably just overridden all those keymaps that don't have a description. Take a look at the updated `:h diffview.defaults` or the default config in the README.

> I think it will be awesome to show a little hint about how to open the help window.

Sure. I already had the intention of adding that, I just didn't consider it a blocker for merging the help panel PR.
