### ISSUE TITLE
Feature: Return remaining count from `next_conflict()`

### ISSUE THREAD

**Issue by marcomayer** [sindrets/diffview.nvim#265]
Is it possible to queue multiple commands to one keymap, I'd like to:
```
		view = {
			["<C-n>"] = actions.next_conflict | actions.select_next_entry,
                 }
```
So that I get the next conflict on C-n but if there's no next conflict, I just get the next file.

**Comment by sindrets** [comment]
@marcomayer The `{rhs}` of the mappings can be a function, so you can call as many actions as you want with whatever logic you want:

```lua
view = {
  ["<C-n>"] = function()
    -- Do whatever you want here...
  end,
}
```

But to accomplish what you're trying to do here we would need `next_conflict` to return a value that indicates the number of remaining conflicts. Something it does not currently do. So should I take this as a feature request to implement that behavior?

**Comment by marcomayer** [comment]
Yes, that would be great, I think returning false if `"#conflicts == 0"` and true otherwise should do the job. If you don't have the time for this let me know and I can come up with a PR later this week. But you probably will add this more quickly than reviewing the PR ;-)

**Comment by sindrets** [comment]
@marcomayer All the conflict navigation actions should now return more than enough data for you to be able to create your described mappings.

For more info, see the updated docs `:h diffview-actions-next_conflict`.
