### ISSUE TITLE
Single "View" File Diffing Support

### ISSUE THREAD

**Issue by harrisoncramer** [sindrets/diffview.nvim#266]
Totally understand if this is out of scope, but was wondering if it's possible to get a single diff view for a file, which includes both deletions and additions.

For instance in Gitlab the additions and subtractions appear in a single view, and are indicated as one or the other via red and green coloring. This is opposed to having the two files sit side by side. Is this possible to configure with this tool?

Thanks again for the awesome plugin, I use it daily!

**Comment by sindrets** [comment]
What you're describing is usually referred to as an inline diff, and we're tracking this feature request in #39 :)
