### ISSUE TITLE
Compare two files

### ISSUE THREAD

**Issue by Shatur95** [sindrets/diffview.nvim#27]
Hi! Thank you a lot for your plugin!
I would like to suggest to add the ability to compare two files.

Something like `DiffviewOpen file1 file2`. When I trying to do so I have the following error:

```
E5108: Error executing lua ...nvim/pack/plugins/opt/diffview.nvim/lua/diffview/lib.lua:67: attempt to index a nil value
```

**Comment by sindrets** [comment]
Do you mean showing the git diff for a number of given paths? This is possible, you have to add two dashes `--` before path args:

`:DiffviewOpen -- file1 file2`

**Comment by Shatur95** [comment]
Thanks for the fast response! But no, I meant to compare these two files with each other. Is it possible?

**Comment by sindrets** [comment]
Oh right. But if you're just diffing two files it's better to just use vim's diff mode. Open your two files in different splits, and in each split call `:diffthis`. If you have only your wanted diff splits open you can do this pretty efficiently with `:windo diffthis`. Then call `:diffoff!` when you're done.

**Comment by Shatur95** [comment]
Oh, of course, thanks!

**Comment by sindrets** [comment]
Actually I just wanna add - because it escaped my mind - it's even easier to just open the first file and then `:diffsplit file2`.

**Comment by Shatur95** [comment]
Did not know, thank you!
