### ISSUE TITLE
[Request] Support for older version of GIT

### ISSUE THREAD

**Issue by vignesh0025** [sindrets/diffview.nvim#270]
Is there any possibility to support older version of Git ? Atleast versions released from last 5 years or something ?

In work environment, tool versions are fixed at the start of the project and there's no simple way to upgrade Git's version.

**Comment by sindrets** [comment]
I'm afraid not. I'm pretty much the sole maintainer of this project, and I don't believe I have the capacity to support multiple git versions. Git 2.31 includes some features that are crucial to how I query the git history.

However, I want to point out that you don't need to install the required Git version system-wide. You can install it wherever you want is your user-space and configure diffview to use that binary with `:h diffview-config-git_cmd`.

**Comment by vignesh0025** [comment]
Thank you for the awesome plugin. **diffview-config-git_cmd** solved the issue.
