### ISSUE TITLE
Mention `:h diff-mode` in the README

### ISSUE THREAD

**Issue by sathishmanohar** [sindrets/diffview.nvim#277]
`]c` jumps to the next hunk and `[c` jumps to the previous hunt but in the `g?` help section it isn't listed.

**Comment by sindrets** [comment]
Yes, because they are builtin mappings: `:h jumpto-diffs`. The plugin assumes you're familiar with everything from `:h diff-mode`.

**Comment by sathishmanohar** [comment]
Got it. This can be mentioned in the readme somewhere
