### ISSUE TITLE
Staging a hunk requires a new DiffView to be opened to refresh

### ISSUE THREAD

**Issue by steliyan** [sindrets/diffview.nvim#280]
I use [gitsigns](https://github.com/lewis6991/gitsigns.nvim) to stage hunks, however the staged changes are not properly shown in DiffView.

How to reproduce:
1. Open a file and add 2 new lines
2. Go to the first line
3. Press `V` (`<S-v>`) for **V-LINE** mode
4. Stage the hunk (the selected line) using `:Gitsigns stage_hunk`

Expected: Diff in `Changes` shows only the second line/Diff in `Staged` shows only the first line
Actual: Diff in `Changes` shows  the first and second lines/Diff in `Staged` does not show any diff (check the attached video)

Reopening using `:DiffViewOpen` fixes the issue, however, this is pretty bad from DX as this breaks my workflow when making and staging changes through DiffView.

https://user-images.githubusercontent.com/1850292/210347148-562898cf-a44c-4d7a-9ddb-d6af341e8aac.mov

**Comment by sindrets** [comment]
Thanks for the report! Should be fixed in the latest commit.

**Comment by steliyan** [comment]
@sindrets, thanks for the quick reaction! The fix works as expected.

This was a big pet peeve of mine, because I heavily use partial staging and I had to resort back to VS Code to double check what was actually staged.

Keep up the good work! :)

**Comment by ghost** [comment]
For me after staging a hunk with gitsigns the diffview window of the current file gets refreshed and moves my cursor to the beginning of the file
