### ISSUE TITLE
Filter after open `:DiffviewFileHistory`

### ISSUE THREAD

**Issue by LintaoAmons** [sindrets/diffview.nvim#292]
Often the case, I want to filter the commit after I `:DiffviewFileHistory`,

So base on what I saw, I want to find the think I'm looking for.

I know that I can use `:DiffviewFileHistory --grep=xxx` to filter commits,
So wonder if it's possible to trigger a filter input popup, when I was in commits buffer, and then filter base on the input.

**Comment by sindrets** [comment]
Yes, that's what the option panel is for. You can open it from the file history panel by pressing `g!` by default. See `:h :DiffviewFileHistory` for more info.

**Comment by LintaoAmons** [comment]
Oh, that's exactly what I want!

One thing to mention is you must `quit` the option panel to make the filter take effect,
If it's possible to make it take effect immediately after a filter was typed in, without leaving the option panel, make it more like interactive.

**Comment by sindrets** [comment]
Updating the file history can take up to several seconds. Having the history update every time you change a flag in the option panel sounds frustrating. I prefer the way it works currently.
