### ISSUE TITLE
Separate highlights for file and panel

### ISSUE THREAD

**Issue by AlexvZyl** [sindrets/diffview.nvim#293]
Hi there!  

I am working on a colorscheme and creating diff colors is turning out to be interesting.  The best I could adjust the colors lead to it looking like this:

![image](https://user-images.githubusercontent.com/81622310/215351501-c0020d13-876f-4657-ac12-80634f4e94a7.png)

This looks okay, but it is quite different to what is usually done.  This leads to the panel looking like this:

![image](https://user-images.githubusercontent.com/81622310/215351533-cd31a659-9192-4ee4-960e-041c9f657811.png)

I am assuming this is because the diff colors are used in the panel.  I can solve this by changing the panel colors using the `BuffEnter` event, but was wondering if you would be keen to use separate highlights for the panel?

**Comment by AlexvZyl** [comment]
P.S. I decided to use the diff colors as the fg since I do not like the way the colors look when darkened or blended with the background.

**Comment by sindrets** [comment]
No, the diff-mode related highlights are not used in the panel. You can find all the highlights defined by this plugin by running:

```vim
:filter /^Diffview/ hi
```

Perhaps you have linked `diffChanged -> DiffChange, diffAdded -> DiffAdd, etc...`. These are not synonymous. The `diff*` (with lower case `d`) highlights are defined by the builtin syntax file for the diff file type. Where as the `Diff*` highlights are used for diff-mode.

Btw, if you're on nvim nightly you can use the `:Inspect` command to find the `extmark` highlights under the cursor.

**Comment by AlexvZyl** [comment]
Ah I see, thank you!
