### ISSUE TITLE
Disable LSP while DiffView is open

### ISSUE THREAD

**Issue by trevarj** [sindrets/diffview.nvim#294]
Is there a way to turn off LSP when diffview is open? 

My usecase is that, when resolving conflicts with diffview, rust-analyzer (maybe other LSPs too) goes crazy due to the conflict markers (`<<<`) and then crashes. I'd like to just fully disable the LSP in this scenario.

**Comment by sindrets** [comment]
There's already an option to disable LSP diagnostics in conflicted files: 

```
:h diffview-config-view.merge_tool.disable_diagnostics
```

If you actually want to fully stop the LSP, then just run `:LspStop`. You can use the `view_enter` + `view_leave` / `view_opened` + `view_closed` hooks to automate this:

```
:h diffview-config-hooks
```

**Comment by trevarj** [comment]
> There's already an option to disable LSP diagnostics in conflicted files

Wow, not sure how I missed this. Thanks!
