### ISSUE TITLE
View only staged (git diff --staged)

### ISSUE THREAD

**Issue by joshmedeski** [sindrets/diffview.nvim#295]
I'd like to view only the hunks I currently have staged. While generating a commit message I want to make this view visible so I can review what's about to be committed.

This is achieved by running `git diff --staged`.

What's the best way to do this? I've looked through the docs and issues and can't figure out a good solution.

**Comment by sindrets** [comment]
`:h :DiffviewOpen`

The option is there

```
:DiffviewOpen --staged
```
