### ISSUE TITLE
"null" title flash when tabbing in between files in DiffviewFilePanel and DiffviewFileHistoryPanel

### ISSUE THREAD

**Issue by charbelnicolas** [sindrets/diffview.nvim#312]
When tabbing or double clicking for the first time on a file while in the DiffviewFilePanel or DiffviewFileHistoryPanel, the window title will flash a "null" text before actually showing the name of the file.

![20230303_152622](https://user-images.githubusercontent.com/14960414/222823822-d06fac0d-1c5c-49cf-9aa0-41778e623324.png)

I don't know if this is hard to fix or impossible but it gets a bit annoying :) and it feels a bit glitchy.

https://user-images.githubusercontent.com/14960414/222824085-7c4b60fd-c193-4fa2-ab7f-dfbac0eb36ff.mp4

**Comment by sindrets** [comment]
This would be difficult to circumvent, and with little benefit.

There is nothing "glitchy" going on. When opening an entry that doesn't have all of it's buffers ready we temporarily load in the null buffer while waiting for git to provide the file content for all the buffers in the layout.
