### ISSUE TITLE
Can't resolve conflicts when cherry-picking

### ISSUE THREAD

**Issue by c3n21** [sindrets/diffview.nvim#313]
Hi!

I've encountered this bug when you try to solve a conflict caused by a cherry-pick.

![image](https://user-images.githubusercontent.com/37077738/222964802-95f10e5e-db54-452e-91ec-86faff082c37.png)

Here is how you can reproduce it:

First create a repo, here is the minimal repo to reproduce this bug
```
git init .
echo "initial content" > file
git status
git add file
git config user.email "test@email"
git config user.name "test@email"
git commit -m "initial commit"
git checkout -b test/cherry-pick
echo "cherry-pick content" >> file
git commit -m "cherry-pick commit"
git switch -
echo "master modified content" >> file
git add -u
git commit -m "new commit"
git cherry-pick test/cherry-pick
```

Now try to open `file` using NeoVim and run :DiffviewOpen and that error will be displayed

**Comment by sindrets** [comment]
Thanks for the report and detailed repro steps! Should be fixed in the latest commit.

**Comment by c3n21** [comment]
Works like a charm, thanks!
