### ISSUE TITLE
Question: How to get word/character level diff highlight? 

### ISSUE THREAD

**Issue by dasupradyumna** [sindrets/diffview.nvim#318]
Hello Sindre!

This is just a question, not an issue as such. I'm sorry, but your setup is just too visually appealing. How do I get the word / character level diff highlighting that can be seen in your README screenshots?
I've tried searching online for a bit, and I've found **diffchar.vim** so far. Could you tell me what you used in your config?

Cheers ~

**Comment by dasupradyumna** [comment]
It was a mistake on my part... some other part of my config was setting `DiffText` group to `DiffChange`, and so the word level diff highlighting was effectively invisible.
Sorry for the noise in the issues.

**Comment by sindrets** [comment]
No worries, glad you figured it out! Just to confirm: I'm not using any plugins to change how the diff highlighting works, I'm only adjusting the highlights.

**Comment by SichangHe** [comment]
For future reference, [diffchar.vim](https://github.com/rickhowe/diffchar.vim) plays pretty nicely with diffview.nvim for word-level diffing, especially when you enable `linematch` in `:h diffopt` the enhance line matching ([my config for reference](https://github.com/SichangHe/.config/commit/1c8d5d03f7593892a280292230a360a07269c9f9#diff-49b84969ad771403dae9052da8f98a1353f5a505927e13df81abf6816b0ce7b8)).

![image](https://github.com/user-attachments/assets/7e1a3381-2db7-4831-ab89-b70c85573b5e)

Hope this helps someone!
Steven Hé (Sīchàng)

**Comment by ychin** [comment]
This is a native feature in Vim/Neovim these days. Just use `:set diffopt+=inline:char` (or `inline:word`) for this. It works better than the diffchar plugin IMO since it's natively implemented by Vim and supports multi-line changes / live updates / multi-file diff / smarter per-char diff heuristics, but it's not a superset of features of diffchar which has some unique features. See https://github.com/vim/vim/pull/16881 (disclaimer: I'm the author of this PR), and https://github.com/neovim/neovim/pull/33086.

**Comment by tienlonghungson** [comment]
> This is a native feature in Vim/Neovim these days. Just use `:set diffopt+=inline:char` (or `inline:word`) for this. It works better than the diffchar plugin IMO since it's natively implemented by Vim and supports multi-line changes / live updates / multi-file diff / smarter per-char diff heuristics, but it's not a superset of features of diffchar which has some unique features. See [vim/vim#16881](https://github.com/vim/vim/pull/16881) (disclaimer: I'm the author of this PR), and [neovim/neovim#33086](https://github.com/neovim/neovim/pull/33086).

@ychin Hi, I updated my nvim using brew upgrade nvim. My nvim now is 0.11.3. But when I run `:set diffopt+=inline:char`, I got this error " Invalid argument: diffopt+=inline:char". It seems like there is no "inline" field in diffopt. Can you help me with this? Thanks

**Comment by ychin** [comment]
Looking at the commits, seems like the changes are in Neovim master branch, but not ported to the `release-0.11` branch. I'm not familiar enough with Neovim's release structure to give you advice, unfortunately. I don't know if it's done on a case-by-case basis or what. You could of course build Neovim from scratch. Or maybe there's a way to suggest inclusion of features into release branches so it could be in the 0.11 branch?

**Comment by tienlonghungson** [comment]
Thank you. I don't know about the release structure either.
