### ISSUE TITLE
Keymap to jump to next / previous conflicts 

### ISSUE THREAD

**Issue by avinashsivaraman** [sindrets/diffview.nvim#321]
I see that we have diff view actions for jumping to next conflicts. Is there any default  keymap to jump to next conflict or is there way to set it?

**Comment by gegoune** [comment]
Try `[x` and `]x`.

**Comment by avinashsivaraman** [comment]
Thanks a lot. Is there any place where I can see all the default keymaps?

**Comment by sindrets** [comment]
https://github.com/sindrets/diffview.nvim/blob/ebcbe90401555272025006db00da0972f7e0db63/doc/diffview_defaults.txt#L94

I'm kinda confused about how you found the action, seemingly without finding the keymaps that are listed both in the README, and the docs.

Anyway, by default you can also press `g?` in any diffview window to get an overview of keymaps related to the current context.

**Comment by avinashsivaraman** [comment]
Thanks.
