### ISSUE TITLE
The 'untracked' git status uses the wrong highlight

### ISSUE THREAD

**Issue by charbelnicolas** [sindrets/diffview.nvim#322]
It looks like the DiffviewStatusUntracked highlight has no effect on untracked files:

![20230316_213612](https://user-images.githubusercontent.com/14960414/225798157-6cd8b540-e619-4fbc-944f-f67297113491.png)

`colors[7]` here is supposed to be pink, not green:

![20230316_213627](https://user-images.githubusercontent.com/14960414/225798159-b5af6a71-dbc5-4dcc-9676-d3b5429f8364.png)

`wal --preview` shows color 7 as pink:

![20230316_213656](https://user-images.githubusercontent.com/14960414/225798161-378ea46d-991e-446d-899d-9edfb4efd8e7.png)

Am I doing something wrong here? Any help is appreciated.

**Comment by sindrets** [comment]
I'm guessing that your color scheme or something else changes it after you call `nvim_set_hl()`. These sort of highlight tweaks should be performed in a `:h ColorScheme` auto command callback such that they are applied after your color scheme.

Another thing to keep in mind: I've seen an anti-pattern of color schemes that use scheduling or similar to set some of their hl groups at some later time. This makes the `ColorScheme` auto command much less useful, as then the color scheme might override your tweaks at some arbitrary point you have no control over. So if you're having trouble figuring out what is overriding the hl, check the source code of your color scheme.

Finally: you can always see the current values of any hl group with:

```
:hi DiffviewStatusUntracked
```

**Comment by charbelnicolas** [comment]
![20230317_101839](https://user-images.githubusercontent.com/14960414/225946945-69a81b08-a439-499e-8c9d-6feb124192e4.png)
![20230317_101854](https://user-images.githubusercontent.com/14960414/225946950-1f2f00a0-761c-4d0e-a322-de0c0c73bac2.png)
![20230317_100940](https://user-images.githubusercontent.com/14960414/225944544-e411f1d9-2987-40a3-80ab-635d0908d493.png)
![20230317_100848](https://user-images.githubusercontent.com/14960414/225944502-ec5fb5e7-0f67-4e3a-9fd2-dd5c9cfd33c2.png)
![20230317_100920](https://user-images.githubusercontent.com/14960414/225944534-b449a315-84b8-409b-9cbd-3452a9c4fd64.png)

Unless the ? means something else other than untracked, I think somewhere in the plugin DiffviewStatusAdded is overriding DiffviewStatusUntracked.

If I change DiffviewStatusAdded to the color I want for the untracked, it works (but now I have pink As all over the place):

![20230317_101334](https://user-images.githubusercontent.com/14960414/225945882-cf736640-dd5a-45f7-a6d4-fcd0519c05db.png)
![20230317_101404](https://user-images.githubusercontent.com/14960414/225945919-75017213-f825-4a88-a6bd-336f427bf58a.png)

![20230317_101310](https://user-images.githubusercontent.com/14960414/225946168-c0de9ea3-6cff-4d8f-87be-7a9130d2bcd7.png)
![20230317_101450](https://user-images.githubusercontent.com/14960414/225946290-6c480c61-20f3-493e-a66c-ff838ed10539.png)
![20230317_101509](https://user-images.githubusercontent.com/14960414/225946293-c27a9a6e-dd02-4593-b1f4-bf67cf6942de.png)

**Comment by charbelnicolas** [comment]
Or maybe it's just that I don't know what the untracked color is for...

**Comment by sindrets** [comment]
Okay, my bad, I see now that I've actually mapped the untracked status to the wrong hl and just never noticed....

https://github.com/sindrets/diffview.nvim/blob/ebcbe90401555272025006db00da0972f7e0db63/lua/diffview/hl.lua#L354

I'll fix it soon.
