### ISSUE TITLE
How can I create a feature like linediff.vim using difffview's UI?

### ISSUE THREAD

**Issue by yutkat** [sindrets/diffview.nvim#328]
I am thinking of using diffview's cool UI to implement a [linediff.vim](https://github.com/AndrewRadev/linediff.vim) feature.

Specifically, I want to compare two buffers and input them into diffview's UI.

Do you have any advice?

**Comment by sindrets** [comment]
Thank you for taking an interest in the project!

Can you explain how our UI would be useful here? The plugin you linked seems like it solves its own problem quite well (diffing and performing edits on two line ranges). What would be done differently in diffview.nvim?

**Comment by yutkat** [comment]
Thanks for your reply.


Specifically, I would want an interface that allows me to compare two buffers.
Any file to the adapter, not just the VCS.
https://github.com/sindrets/diffview.nvim/blob/052521c8948491c20f4e9278864ff058c6bb7436/lua/diffview/lib.lua#LL29-L34C5

**Comment by sindrets** [comment]
You can diff the current buffer against another one with:

```vim
:diffsplit {filename}
```

If you wanna compare more than two buffers, you can simply open the buffers you wanna compare and then `:diffthis`. When you're done diffing, do `:diffoff!`.

**Comment by yutkat** [comment]
That is true. but I just wanted to unify the diff UI into diffview.

I understand it's not easy to do, so I'd like to close this issue for now.

**Comment by yutkat** [comment]
I found that this plugin can do what I want.
https://github.com/antosha417/nvim-compare-with-clipboard
