### ISSUE TITLE
Error on last update

### ISSUE THREAD

**Issue by augustocdias** [sindrets/diffview.nvim#338]
After last update I'm having this error when calling setup:

```Failed to run `config` for diffview.nvim

....local/share/nvim/lazy/diffview.nvim/lua/diffview/hl.lua:129: attempt to call field 'nvim_get_hl' (a nil value)

# stacktrace:
  - /diffview.nvim/lua/diffview/hl.lua:129 _in_ **get_hl**
  - /diffview.nvim/lua/diffview/hl.lua:166 _in_ **get_hl_attr**
  - /diffview.nvim/lua/diffview/hl.lua:185 _in_ **get_fg**
  - /diffview.nvim/lua/diffview/hl.lua:466 _in_ **update_diff_hl**
  - /diffview.nvim/lua/diffview/hl.lua:475 _in_ **setup**
  - /diffview.nvim/lua/diffview/init.lua:25 _in_ **init**
  - /diffview.nvim/lua/diffview/init.lua:260
  - ~/.config/nvim/lua/plugins/ui.lua:36 _in_ **config**
  - ~/.config/nvim/init.lua:18
 ```

Running on nvim nightly.

**Comment by sindrets** [comment]
You're running an outdated nightly build. Recompile from master.
