### ISSUE TITLE
`DiffDelete` highlight used in expected places

### ISSUE THREAD

**Issue by egargan** [sindrets/diffview.nvim#340]
There are a few situations where Diffview uses the `DiffDelete` highlight group, where it seems it'd make more sense to use `DiffviewDiffDelete` or `DiffviewDiffAddAsDelete`.

I have my coloursheme set up as follows.

```lua
highlights["DiffDelete"] = { bg = "#5A424D", fg = "none" } -- Red
highlights["DiffviewDiffAddAsDelete"] = { bg = "none", fg = "#4C566A" } -- Dark grey
highlights["DiffviewDiffDelete"] = { bg = "none", fg = "#4C566A" } -- Dark grey
highlights["DiffAdd"] = { bg = "#45504F" } -- Green
highlights["DiffChange"] = { bg = "#54524F" } -- Yellow
highlights["DiffText"] = { bg = "#70695A" } -- Lighter yellow
```

This looks great for the most part, for files with single or few-line diffs, e.g.

<img width=500 src="https://user-images.githubusercontent.com/27496517/229844660-4111f773-623f-4a10-a505-6cb0438c79ca.png">

But when diffs span entire files, e.g. when a file is added, it appears `DiffDelete` is applied, which seems inappropriate.

<img width=500 src="https://user-images.githubusercontent.com/27496517/229845109-2bc53cdc-0bfe-40f4-8f89-01517038625c.png">

<details>
  <summary>The same goes for files that have been deleted...</summary>
  <img width=500 src="https://user-images.githubusercontent.com/27496517/229845305-f02d38ad-a129-4bb3-9dc4-5d14e43161b8.png">
</details>

<details>
  <summary>As well as merge conflict views...</summary>
<img width=500 src="https://user-images.githubusercontent.com/27496517/229845965-09a1dd9b-c557-4770-9720-79024832746c.png">
</details>

Do you think it'd make sense to change the highlight groups used in these scenarios? Or can you suggest another change that might fix these odd-looking colours? Happy to have a go myself with a bit of guidance.

**Comment by dasupradyumna** [comment]
> `enhanced_diff_hl` only applies to `diff2*` layouts, so this won't change anything for merge tool layouts. I realize this wasn't very clear in the documentation, so I have amended the docs to clarify this.

@sindrets Is extending `enhanced_diff_hl` to apply to merge tool layout in the future of this plugin? I think it will improve the uniformity of colors across the **Diffview**s.

**Comment by sindrets** [comment]
@dasupradyumna What would you expect `enhanced_diff_hl` to do in a 3-way diff? 2-way diffs in VCS are in a unique position. It's a comparison between old state on one side, and new state on the other. As such, a diff "insertion" in the old state actually represents a deletion from the perspective of the new state.

This same logic does not apply to 3-way diffs, where you have one version for each merge parent, as well as the result from the merge. Highlighting insertions as deletions does not make sense in any of these states.

**Comment by dasupradyumna** [comment]
I am not aware of the specifics of the implementation, so I apologize if I asked something unreasonable.

![status_merge](https://github.com/sindrets/diffview.nvim/assets/45595032/8013d9bc-0c96-4848-94f1-b4d5415ee22d)

I was simply wondering whether it's possible to color the red "deletion" regions in 3-way (or 4-way) merge layout to be grey like a 2-way diff between 2 states. If it's not, I understand. :)

**Comment by sindrets** [comment]
> I'm tempted to suggest an optional set of highlight groups for Diffview, e.g. DiffviewDiffAdd, DiffviewDiffDelete, to avoid conflicts between Git plugins, and let us make both Diffview and other plugins as beautiful as possible.

@egargan granted!

@dasupradyumna after the latest commit `enhanced_diff_hl` will highlight the diff delete fill-chars more subtly in *all* layouts. Not only the `diff2*` layouts. And if you wish to change this highlight without messing with how `DiffDelete` is used in other contexts, you can simply adjust `DiffviewDiffDelete`.

---

Including the full commit message below for additional clarity:

```
Adds new highlight groups shadowing all the default diff highlights:

- `DiffviewDiffAdd` -> `DiffAdd`
- `DiffviewDiffDelete` -> `DiffDelete`
- `DiffviewDiffChange` -> `DiffChange`
- `DiffviewDiffText` -> `DiffText`

These are set as 'winhl' in all the diff buffers created by the plugin.
This way users will be able to change the diff highlighting for Diffview
only, without affecting the use of these groups outside of the plugin.

OTHER CHANGES:

Having `enhanced_diff_hl` enabled will now highlight delete fill-chars
more subtly in *all* layouts. Not only `diff2*` layouts.
```

**Comment by dasupradyumna** [comment]
Thanks a lot for the lightning fast response! ❤️ 

![status_merge](https://github.com/sindrets/diffview.nvim/assets/45595032/d8cf4a88-0388-4508-8d03-889f2470f731)

It works as expected now, I needed this change to include in my new colorscheme [plugin](https://github.com/dasupradyumna/midnight.nvim).
Cheers mate ~
