### ISSUE TITLE
Plugin isn't working at all

### ISSUE THREAD

**Issue by RizaHKhan** [sindrets/diffview.nvim#342]
When running the command `:DiffviewFileHistory` I get the following error:

![image](https://user-images.githubusercontent.com/51720003/230633595-253f6eaf-c90b-4c25-ad49-0c94d7eb4932.png)

This has just started to happen recently and I am unable to use the plugin at all across different types of editors (Lunarvim, Lazy Nvim) and across systems (my Linux system or my Mac).

Anyone else seeing this as well?

**Comment by sindrets** [comment]
#337
