### ISSUE TITLE
Draw empty winbar in one side if other has winbar

### ISSUE THREAD

**Issue by ArtAndreev** [sindrets/diffview.nvim#348]
I face the next problem: I have barbecue installed, that draws winbar. When I start diffview against HEAD and another revision or just against another revision (the same case, I guess), I have the right side with a winbar drawn, because right side is a buffer with LSP-server attached. The left side doesn't has a winbar:

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/26388769/233689036-517b4428-7f77-4d8e-b839-a586c57f28e1.png">

The diff between two sides isn't aligned. The workaround is to disable barbecue with `:Barbecue toggle`, but it's not convenient.

I think, one of the possible solutions can be to set a winbar in the left side to some empty string, so it's drawn as empty line and content is aligned.

**Comment by sindrets** [comment]
Try:

```lua
require("diffview").setup({
  view = {
    default = {
      winbar_info = true,
    },
    file_history = {
      winbar_info = true,
    },
  },
})
```

**Comment by ArtAndreev** [comment]
It works, thanks!

<details>
<summary>Result</summary>
  
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/26388769/233792428-fdef2a82-2201-4dd1-b590-fbba95533068.png">
  
</details>

Can it be activated in smart way?

**Comment by sindrets** [comment]
What do you mean "smart way"? You put that snippet in your config.

**Comment by ArtAndreev** [comment]
Plugin may detect winbar in the right side (`vim.o.winbar`) and add winbar to the left side automatically, if it is missing.

**Comment by ArtAndreev** [comment]
Maybe it should activate these two options automatically, for example.

**Comment by sindrets** [comment]
Ah, I see what you mean. No, I strongly dislike "smart" options. They lead to unpredictable behavior.

If you want diffview to set the winbar, we have an option for it, and you can set it in your own config.

**Comment by ArtAndreev** [comment]
Understood, thanks for the help!
