### ISSUE TITLE
[feature]: Support `--walk-reflogs` flag option in file-history

### ISSUE THREAD

**Issue by thenbe** [sindrets/diffview.nvim#353]
Hi. Is there a way to get the stash, where the output would be similar to:

```bash
git stash list
git log -g stash
lazygit stash
```

I would've thought the following would work similar to `git log -g stash`, but the `-g, --walk-reflogs` flag is not supported at the moment:

```vim
DiffviewFileHistory -g --range=stash
```

As a workaround, I found this to work but it's missing the stash index (`stash@{2}`):

```vim
DiffviewFileHistory --reflog --merges --grep='^WIP|^On'
```

**Comment by sindrets** [comment]
We can add support for `--walk-reflogs`. I imagine that should be pretty straight forward. However, I don't have time to work on this at the moment. PR's are welcome.
