### ISSUE TITLE
USAGE page seems to have a typing error.

### ISSUE THREAD

**Issue by greyHairChooseLife** [sindrets/diffview.nvim#355]
Here is [link](https://github.com/sindrets/diffview.nvim/blob/main/USAGE.md#comparing-changes-from-the-individual-pr-commits) for the USAGE page.

There you can see right away like below. It has triple dots between git-revs.

`:DiffviewFileHistory --range=origin/main...HEAD --right-only --no-merges`

I cared nothing but only `--range`. So I set my default like `:DiffviewFileHistory --range=origin/main...HEAD`. And it returns me like...

from : arbitrary commit (but fixed at least)
to : HEAD

And then I found there are only 2 dots for the option `--range` in README and :help page. That made me happy finally.

Since I couldn't find anywhere about triple dots for the option, I leave here issue for a typing error.

Thanks for the lovely plugin. God bless you.

**Comment by sindrets** [comment]
It's not a typo. Two-dot and three-dot rev ranges do not describe the same set of commits.

<details>
  <summary><b>"Dotted Range Notations" from <code>man git-rev-parse</code></b></summary>

```
Dotted Range Notations
    The .. (two-dot) Range Notation
        The ^r1 r2 set operation appears so often that there is a shorthand
        for it. When you have two commits r1 and r2 (named according to the
        syntax explained in SPECIFYING REVISIONS above), you can ask for
        commits that are reachable from r2 excluding those that are
        reachable from r1 by ^r1 r2 and it can be written as r1..r2.

    The ... (three-dot) Symmetric Difference Notation
        A similar notation r1...r2 is called symmetric difference of r1 and
        r2 and is defined as r1 r2 --not $(git merge-base --all r1 r2). It
        is the set of commits that are reachable from either one of r1
        (left side) or r2 (right side) but not from both.
```
</details>

Take for instance this example commit graph:

![image](https://user-images.githubusercontent.com/2786478/236624326-b939acec-2b08-4414-aea0-38a6f3b7d0d8.png)

Here we have two branches, `main` and `feature`, that have diverged. If we perform a symdiff on these two branches we get this set of commits:

![image](https://user-images.githubusercontent.com/2786478/236624354-e6f60436-7a5f-4779-a550-96c387dcbbdc.png)

Using `--cherry-pick` options we can specify which side of the symdiff we care about:

![image](https://user-images.githubusercontent.com/2786478/236624368-56efcd9d-a5d3-43c0-9971-84195e0061c9.png)

![image](https://user-images.githubusercontent.com/2786478/236624376-dbb612c8-deb1-472f-93e6-7775a18df2dc.png)

**Comment by greyHairChooseLife** [comment]
oh, I see.

As a beginner, I used to `git diff` for staged or unstaged files. Or to compare two of whole branches before I merge just-fetched upstream/*.

Yet no experienced the conflict between two branches but only between some commits when I rebase my own code.

But now your answer made sense to me very well. Thank you for your kindness, despite my dumb issue.
