### ISSUE TITLE
I can't interact with the plugin apart from moving up and down

### ISSUE THREAD

**Issue by CristoAMH** [sindrets/diffview.nvim#37]
I open the plugin with the :DiffviewOpen and I can "j" and "k" but when I press anything else like "tab" or "enter" the file doesn't change, I lose my pointer and I can't interact with neovim. I can't even quit.

The only thing I have done to installed it was adding this line  `use 'sindrets/diffview.nvim'`
My Nvim version is: VIM v0.6.0-dev+8-g75f758b99

**Comment by sindrets** [comment]
> when I press anything else like "" or "" the file doesn't change

When you press what?

And what files are you trying to change? Files created from git history are set to be un-modifiable. That means when you are comparing against the index (i.e. when you call `:DiffviewOpen` with no args) only the buffer in the right window is modifiable.

**Comment by CristoAMH** [comment]
@sindrets I updated the issue I wrote <tab> and <cr> but did not render correctly.
 
 I don't quire understand about what you mean about which files am I trying to change? Basically I changed a few files in my project, then I do :DiffviewOpen and it works correctly it shows the diff between the first file in the list and HEAD, but then I do "j" to go to the second file and press enter and as I said the file on the preview did not change, my pointer in the filelist disappear and I can't interact anymore with the editor.

**Comment by sindrets** [comment]
I'm seeing it now. It's happening on the latest version of neovim. It didn't happen before. So it's definitely related to a recent change, but I don't know what yet. Going to have to investigate this further.

**Comment by sindrets** [comment]
@CristoAMH Seems to have been related to [this commit in nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/commit/625017df3e1e347ba35e7d6ef7a56efd096e8963). At least it was for me. That commit has now been reverted. If you are using that plugin please update it and let me know if that resolved the problem.

**Comment by CristoAMH** [comment]
@sindrets I am kind of curious how do you manage to know that was the problem, but yes, Indeed it was. After updated it works like a charm. You are the best.

**Comment by sindrets** [comment]
> I am kind of curious how do you manage to know that was the problem

I was kind of lucky: I saw a post on reddit about a similar problem where one of the maintainers of lspconfig was able to explain the issue. But if that wasn't the case, the way you tackle these sort of problems is by doing a manual binary search through your plugins to find the problematic plugin:

- Disable half of your plugins
- If the problem persists you know the problematic plugin is in the active half. Otherwise it's in the inactive half.
- Keep dividing the problematic set of plugins in half until you find the offender.
