### ISSUE TITLE
[Bug] keymaps override issue in LazyVim

### ISSUE THREAD

**Issue by 2nthony** [sindrets/diffview.nvim#382]
### Description

in LazyVim.

I has some custom keymaps which conflicts to diffview default keymaps.
<img width="1056" alt="image" src="https://github.com/sindrets/diffview.nvim/assets/19513289/baf1b097-5e70-4e0d-bb66-ecfaa6780629">

so if i open the diffview panel and press `<leader>c`, which key will appear
<img width="1143" alt="image" src="https://github.com/sindrets/diffview.nvim/assets/19513289/8f5e8998-35b8-4d5e-9384-e65b259cc212">

### Expected behavior

i am not sure if is the priority problem and not sure if these can.🙏

expected:
- set the keymaps when diffview open.
- restore the keymaps when diffview close or exit

### Actual behavior

-

### Steps to reproduce

-

### Health check

<details>
<summary>Output of <code>:checkhealth diffview</code></summary>

```

==============================================================================
diffview: require("diffview.health").check()

Checking plugin dependencies ~
- OK nvim-web-devicons installed.

Checking VCS tools ~
- The plugin requires at least one of the supported VCS tools to be valid.
- OK Git found.
- OK Git is up-to-date. (2.39.2)
- WARNING Configured `hg_cmd` is not executable: 'hg'


```

</details>

### Neovim version

```markdown
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 13.4

**Comment by sindrets** [comment]
What exactly is the problem here?

> expected:
>   - set the keymaps when diffview open.
>   - restore the keymaps when diffview close or exit

The plugin already does this.

**Comment by 2nthony** [comment]
ok, thanks to letting me know. I'll try to figure out the reason is.

**Comment by sindrets** [comment]
Closing until more info is provided.
