### ISSUE TITLE
Show unsaved buffer / file changes

### ISSUE THREAD

**Issue by uloco** [sindrets/diffview.nvim#390]
I am not quite sure if I can use this plugin to show unsaved buffer changes before I save a file. So I mean not concerning git but local file state vs dirty buffer state. Is this possible?

**Comment by sindrets** [comment]
No need for a plugin to do this. The vim docs already describe how to set up a simple command to achieve this: `:h diff-original-file`.

[I use a slight variation on this command myself.](https://github.com/sindrets/dotfiles/blob/1990282dba25aaf49897f0fc70ebb50f424fc9c4/.config/nvim/lua/user/lib.lua#L175)

**Comment by uloco** [comment]
Ty I'll give it a try
