### ISSUE TITLE
[Feature] File name on the top of the diff window

### ISSUE THREAD

**Issue by briandipalma** [sindrets/diffview.nvim#391]
### Description

Doubt this can be done but thought it was worth asking. To reduce the amount of looking back and forwards from the file panel to the diff panel it would be nice to have the filename fully across the top of the diff window. As a header basically. Something like this:

![image](https://github.com/sindrets/diffview.nvim/assets/1597820/edcde32f-b9ae-49c6-ae6f-ec0272ba1394)

### Actual behavior

.

### Steps to reproduce

.

### Health check

.

### Neovim version

```markdown
.
```

### Operating system and version

.

**Comment by sindrets** [comment]
There's already a way to enable this if you're on nvim ≥ v0.8:

```lua
require("diffview").setup({
  view = {
    default = {
      winbar_info = true,
    },
    file_history = {
      winbar_info = true,
    },
  },
})
```

**Comment by briandipalma** [comment]
You need to focus into the file in the diff splits though. It only goes across the top of one of the splits too which makes it cramped and it's the same value in every split so I feel it makes sense for it to be a header over all the splits. My ideal workflow is to be able to quickly move over all the diffs without having to focus in on the split panel while keeping my eyes on the split panel. Moving from change to change/file to file is why I asked for the `[c` and `]c` bindings. And the header means you wouldn't have to scan the file list to figure out where you are in a large review.

**Comment by sindrets** [comment]
> You need to focus into the file in the diff splits though. It only goes across the top of one of the splits too \[...]

No, this is not the default behavior. You likely have plugins interfering with the winbar. By default it should look more like this:

![2023-07-10-194028_maim](https://github.com/sindrets/diffview.nvim/assets/2786478/9fc1591e-a35a-4381-9955-049b0a75f44f)

It shows the Git object name in the winbar of each of the diffed buffers. You don't have to focus the window for the winbar to show up.

> \[...] so I feel it makes sense for it to be a header over all the splits

As in *one single header* that spans multiple windows? That's not something I'm interested in working on. I'm not convinced it's sufficiently more useful than what we can already do with the builtin winbar.

In my own setup I use my own custom winbar that gives me the information I need at a glance:

![image](https://github.com/sindrets/diffview.nvim/assets/2786478/8ac2666a-e6fe-4e11-b158-84a4e914e61a)

**Comment by briandipalma** [comment]
Correct my config for lualine was causing it not to appear. Sorry for the bother.
