### ISSUE TITLE
[Bug] error in corouting when switching files

### ISSUE THREAD

**Issue by emmanueltouzery** [sindrets/diffview.nvim#392]
### Description

when reviewing a diff using diffview, and quickly switching the current file using `<tab>`, I got this coroutine error message.

### Actual behavior

<details>
<pre>
Error executing vim.schedule lua callback: ...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:179: The coroutine failed with this message: 
	context: cur_thread=main co_thread=<thread 0x7f64283dc738> co_func=...ack/packer/start/diffview.nvim/lua/diffview/vcs/file.lua:199
...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:179: The coroutine failed with this message: 
	context: cur_thread=<thread 0x7f64283dc738> co_thread=<thread 0x7f64283db9f0> co_func=...packer/start/diffview.nvim/lua/diffview/scene/window.lua:92
...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:179: The coroutine failed with this message: 
	context: cur_thread=<thread 0x7f64283db9f0> co_thread=<thread 0x7f6422115470> co_func=...iffview.nvim/lua/diffview/scene/views/diff/diff_view.lua:193
...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:179: The coroutine failed with this message: 
	context: cur_thread=<thread 0x7f64283db9f0> co_thread=<thread 0x7f64265f2080> co_func=...nvim/lua/diffview/scene/views/standard/standard_view.lua:134
...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:179: The coroutine failed with this message: 
	context: cur_thread=<thread 0x7f64283db9f0> co_thread=<thread 0x7f64265f37b0> co_func=...tart/diffview.nvim/lua/diffview/scene/layouts/diff_2.lua:46
...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:179: The coroutine failed with this message: 
	context: cur_thread=<thread 0x7f64283db9f0> co_thread=<thread 0x7f64265f4160> co_func=...packer/start/diffview.nvim/lua/diffview/scene/layout.lua:163
...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:179: The coroutine failed with this message: 
	context: cur_thread=<thread 0x7f64283db9f0> co_thread=<thread 0x7f64283dadf8> co_func=...packer/start/diffview.nvim/lua/diffview/scene/window.lua:124
...packer/start/diffview.nvim/lua/diffview/scene/window.lua:146: Expected Lua number
stack traceback:
	[C]: in function 'nvim_win_set_buf'
	...packer/start/diffview.nvim/lua/diffview/scene/window.lua:146: in function <...packer/start/diffview.nvim/lua/diffview/scene/window.lua:124>
	[C]: in function 'xpcall'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:354: in function <...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:351>
stack traceback:
	[C]: in function 'error'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:362: in function <...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:351>
stack traceback:
	[C]: in function 'error'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:179: in function 'raise'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:298: in function 'await'
	...packer/start/diffview.nvim/lua/diffview/scene/layout.lua:184: in function <...packer/start/diffview.nvim/lua/diffview/scene/layout.lua:163>
	[C]: in function 'xpcall'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:354: in function <...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:351>
stack traceback:
	[C]: in function 'error'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:362: in function <...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:351>
stack traceback:
	[C]: in function 'error'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:179: in function 'raise'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:298: in function 'await'
	...tart/diffview.nvim/lua/diffview/scene/layouts/diff_2.lua:54: in function <...tart/diffview.nvim/lua/diffview/scene/layouts/diff_2.lua:46>
	[C]: in function 'xpcall'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:354: in function <...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:351>
stack traceback:
	[C]: in function 'error'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:362: in function <...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:351>
stack traceback:
	[C]: in function 'error'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:179: in function 'raise'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:298: in function 'await'
	...nvim/lua/diffview/scene/views/standard/standard_view.lua:162: in function <...nvim/lua/diffview/scene/views/standard/standard_view.lua:134>
	[C]: in function 'xpcall'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:354: in function <...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:351>
stack traceback:
	[C]: in function 'error'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:362: in function <...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:351>
stack traceback:
	[C]: in function 'error'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:179: in function 'raise'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:298: in function 'await'
	...iffview.nvim/lua/diffview/scene/views/diff/diff_view.lua:203: in function 'func'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:366: in function <...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:351>
stack traceback:
	[C]: in function 'error'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:179: in function 'raise'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:207: in function 'step'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:239: in function 'notify_all'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:205: in function 'step'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:239: in function 'notify_all'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:205: in function 'step'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:239: in function 'notify_all'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:205: in function 'step'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:239: in function 'notify_all'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:205: in function 'step'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:239: in function 'notify_all'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:395: in function 'callback'
	...packer/start/diffview.nvim/lua/diffview/scene/window.lua:106: in function <...packer/start/diffview.nvim/lua/diffview/scene/window.lua:92>
	[C]: in function 'xpcall'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:354: in function <...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:351>
stack traceback:
	[C]: in function 'error'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:362: in function <...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:351>
stack traceback:
	[C]: in function 'error'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:179: in function 'raise'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:207: in function 'step'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:239: in function 'notify_all'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:395: in function 'callback'
	...ack/packer/start/diffview.nvim/lua/diffview/vcs/file.lua:293: in function <...ack/packer/start/diffview.nvim/lua/diffview/vcs/file.lua:199>
	[C]: in function 'xpcall'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:354: in function <...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:351>
stack traceback:
	[C]: in function 'error'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:362: in function <...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:351>
stack traceback:
	[C]: in function 'error'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:179: in function 'raise'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:207: in function 'step'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:239: in function 'notify_all'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:214: in function 'step'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:392: in function <...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:384>
	[C]: in function 'resume'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:185: in function 's
</pre>
</details>

### Steps to reproduce

didn't attempt to reproduce in a clean config.

### Health check

<details>
<summary>Output of <code>:checkhealth diffview</code></summary>

```
==============================================================================
diffview: require("diffview.health").check()

Checking plugin dependencies ~
- OK nvim-web-devicons installed.

Checking VCS tools ~
- The plugin requires at least one of the supported VCS tools to be valid.
- OK Git found.
- OK Git is up-to-date. (2.41.0)
- WARNING Configured `hg_cmd` is not executable: 'hg'

```

</details>

### Log info

<details>
<summary>Relevant info from <code>:DiffviewLog</code></summary>

```
[INFO  2023-07-06 15:36:35.466 +0200] ...ite/pack/packer/start/diffview.nvim/lua/diffview/lib.lua:24: [command call] :DiffviewOpen develop...
[INFO  2023-07-06 15:36:36.187 +0200] ...iffview.nvim/lua/diffview/scene/views/diff/diff_view.lua:483: [DiffView] Completed update for 45 files successfully (180.101 ms)
[ERROR 2023-07-06 15:41:13.401 +0200] ...tart/diffview.nvim/lua/diffview/vcs/adapters/hg/init.lua:50: [HgAdapter] Configured `hg_cmd` is not executable: 'hg'
```

</details>

### Neovim version

```markdown
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 6.3.8-200.fc38.x86_64 x86_64 GNU/Linux

**Comment by sindrets** [comment]
The error should now be correctly handled, after the latest commit.

**Comment by emmanueltouzery** [comment]
yes, this fixes it, thank you!

I tried to torture test it a little more (although I got this error through legit everyday use), and then I got another ugly error, but really after torture testing it massively. But looking at the error in detail, it was "cannot start process /usr/bin/git, too many open files", and at that point I decided that this way enough torture testing :)

thank you!

**Comment by sindrets** [comment]
Thank you for testing and reporting back!
