### ISSUE TITLE
How to remove this Breadcrumb when diff

### ISSUE THREAD

**Issue by LintaoAmons** [sindrets/diffview.nvim#393]
<img width="1271" alt="image" src="https://github.com/sindrets/diffview.nvim/assets/95092244/670d4cf4-e4e5-4cc5-b930-f8fd548a235f">

**Comment by sindrets** [comment]
Those bread crumbs are from a plugin you're using. Looks like lspsaga.nvim. You'll have to look to that plugin's docs to find out if you can configure its winbar.

Basically what you want to do is to disable the winbar in any window that has the `'diff'` window option set.

Optionally you can enable winbars in all of diffview's buffers as well with these settings:

```lua
require("diffview").setup({
  view = {
    default = {
      winbar_info = true,
    },
    file_history = {
      winbar_info = true,
    },
  },
})
```

**Comment by LintaoAmons** [comment]
Thx~ 

Can I ask another question in this thread? I always want to use `c` to trigger commit pane.
So how can I add a custom keybinding when I'm  in `Diffview` buffer?

Like I can press `S` to `Stage all`
I want to map some custom function to `c`
