### ISSUE TITLE
Highlights

### ISSUE THREAD

**Issue by AndreM222** [sindrets/diffview.nvim#398]
Hi, I am trying to set up my dracula theme setup to work with the highlights. But why does it look like you have many types. I can see you have red, green, blue, and the dashed ones.

![image](https://github.com/sindrets/diffview.nvim/assets/98118238/abfd1814-7ee2-4d59-9008-4dee10a26c5d)

![image](https://github.com/sindrets/diffview.nvim/assets/98118238/be85465e-2b06-4b75-9ca4-50858af07ec3)

![image](https://github.com/sindrets/diffview.nvim/assets/98118238/1cde491b-7e77-4021-84ed-31d65f859fb0)

**Comment by sindrets** [comment]
We're only using the default diff highlights described under `:h hl-DiffAdd`. The screenshot you shared also uses our `:h diffview-config-enhanced_diff_hl` config option, which does some smart `'winhl'` linking depending on the layout. Check the help page to see an explanation of what it does.
