### ISSUE TITLE
Toggle stage entry in view

### ISSUE THREAD

**Issue by marcushwz** [sindrets/diffview.nvim#40]
Thank you so much for this plugin, I have been enjoying it with Neogit. 

Here is a quick question on whether it is possible to toggle stage entry in view like the one we have in the file panel?
My workflow is something like this after I am done with a feature, I will go through all the changes locally through `Diffview` but I see myself going back and forth between the `view` and the `file panel` to stage a file.

Not sure if this is a good idea or possible. But will love to hear from you. Thanks again for this amazing plugin.

``` lua
    view = {
      ["<tab>"]     = cb("select_next_entry"),  -- Open the diff for the next file 
      ["<s-tab>"]   = cb("select_prev_entry"),  -- Open the diff for the previous file
      ["<leader>e"] = cb("focus_files"),        -- Bring focus to the files panel
      ["<leader>b"] = cb("toggle_files"),       -- Toggle the files panel.
      -- ["-"] = cb("toggle_stage_entry")
    },
```

**Comment by sindrets** [comment]
This already works. Just add a key binding for it in the view key bindings in the config. The file panel has to be open for it to work though.

**Comment by marcushwz** [comment]
Ohh, okay 🤣 . Sorry about this, I didn't know it is already working. Do you think it's a good idea to get it working with the file panel close? Seems like navigating with `tab` works fine with the file panel closed. If you think we can work on it, I would love to contribute a PR.

**Comment by sindrets** [comment]
If you would like to contribute a PR, please go ahead! This should be pretty simple. I think you should add a new callback for this as `toggle_stage_entry` stages the file under the cursor in the file panel, and it would be confusing if it sometimes targeted the current open file. Perharps `toggle_stage_open_file` or something similar. You should start looking at how [the other callbacks are implemented](https://github.com/sindrets/diffview.nvim/blob/1936824f5986c986befad5995e7bf87ba124d109/lua/diffview.lua#L133).
