### ISSUE TITLE
[Feature request] option to toggle absolute timestamps in DiffviewFileHistory

### ISSUE THREAD

**Issue by RayJameson** [sindrets/diffview.nvim#402]
Hello! Thank you for great plugin, I would really like to have option to toggle absolute timestamps instead of relative. Sometimes I need to check if some change was before or after some certain point in time.

**Comment by sindrets** [comment]
> Sometimes I need to check if some change was before or after some certain point in time.

In that case you're probably better off using the `--before=` and `--after=` flag options. Also worth noting is that you can always press `L` with the cursor over any commit in the file history panel and you'll get the full `git show` output for that commit. Which includes the exact timestamp.

**Comment by RayJameson** [comment]
Thanks, both options seem reasonable for me
