### ISSUE TITLE
[Feature] Add `s` and `u` default keybindings?

### ISSUE THREAD

**Issue by briandipalma** [sindrets/diffview.nvim#404]
Just like `S` and `U` but to stage/unstage individual files?

**Comment by sindrets** [comment]
We already have https://github.com/sindrets/diffview.nvim/blob/e91110d2a7f8e2f667666aba6ea089ff823f8748/doc/diffview_defaults.txt#L147

In my opinion there's no reason for stage/unstage file to be two separate mappings. It's never ambiguous which action should be taken. If the file is staged, "unstage" is the only action that can be taken. If the file is unstaged, "stage" is the only action that can be taken. This is why we only offer a toggle for this action. You can of course map this to both `s` and `u` if you want.

**Comment by briandipalma** [comment]
Yeah, I agree, but `-` is more awkward to type then either `s` or `u`. There are multiple keymaps for some of the other operations, maybe adding a default `s` keymap that toggles would be OK?

**Comment by sindrets** [comment]
Yeah sure, that makes sense. I initially decided on using the `-` mapping for the sake of familiarity from vim-fugitive.
