### ISSUE TITLE
Error on DiffView close

### ISSUE THREAD

**Issue by xbladesub** [sindrets/diffview.nvim#408]
Are there any ideas?
![image](https://github.com/sindrets/diffview.nvim/assets/45129790/37aad3a7-6f80-4005-aad2-2d707de124cb)

**Comment by sindrets** [comment]
Reading the stack trace, you can see that this error is being raised from `nvim-ts-rainbow`. I'm guessing you're using the original, unmaintained version of the plugin, which started causing problems like this some time ago as it's no longer keeping up with upstream changes in `nvim-treesitter`. I recommend that you replace this plugin with one of the maintained forks like i.e. https://github.com/hiphish/rainbow-delimiters.nvim.
