### ISSUE TITLE
Curious about the cursor line and background for diff deleted

### ISSUE THREAD

**Issue by Alienover** [sindrets/diffview.nvim#41]
![image](https://user-images.githubusercontent.com/12182069/125165795-2167e600-e1cb-11eb-9624-26f4bfa2c3fd.png)

1. About the cursor line, I am curious about how you solve this https://github.com/neovim/neovim/issues/9800.

2. About the background for diff deleted, how did you get those stripes on it?

**Comment by sindrets** [comment]
1. I don't solve that. I get an underline when the cursor is over a highlighted diff. It doesn't bother me though.
2. See my reply in #35.

**Comment by Alienover** [comment]
For #2, that's really helpful. Thx.
