### ISSUE TITLE
Show diff of current file git history

### ISSUE THREAD

**Issue by simouel** [sindrets/diffview.nvim#42]
It would be great if we could load every revision of a file into the left pane and then browse the diff.
I feel I could be able to do this if you are interested. (maybe with a little bit of guidance)

**Comment by sindrets** [comment]
This is a great idea! I'm on vacation at the moment and therefore I won't be able to work on this for a while. If you want to give this a go yourself, please go ahead! I think it's gonna require some refactoring of [the file panel](https://github.com/sindrets/diffview.nvim/blob/main/lua/diffview/file-panel.lua) and the way it is used in [the view](https://github.com/sindrets/diffview.nvim/blob/main/lua/diffview/view.lua).

**Comment by tcstory** [comment]
interesting!!!!
