### ISSUE TITLE
How can I just compare 2 buffers ? (non-git files)

### ISSUE THREAD

**Issue by searleser97** [sindrets/diffview.nvim#420]

**Comment by searleser97** [comment]
so, just noticed this plugin doesn't really add any nice UI, it just uses the default/builtin diff view from vim which is already good enough. This plugin just helps with git-like stuff

**Comment by sindrets** [comment]
We do have UI, but the diff is driven by the builtin diff-mode. As is described in the README. This is a very VCS centered plugin. If you just wanna compare any two files, just use the builtin `:h :diffsplit` command.
