### ISSUE TITLE
[feature] Add actions for selecting first / last entry

### ISSUE THREAD

**Issue by emmanueltouzery** [sindrets/diffview.nvim#421]
Hello, I use diffview in a way that I select the current file when opening, using `--selected-file=`. This works great for me.

However sometimes I want to use diffview to review all the changes. So, I open the diff view, the current file selected, but I'd like to jump to the first file to go through all the files one by one and be sure I didn't miss any of them. I don't know a way to do that... I know of:
```
lua require'diffview.config'.actions.select_next_entry()
```

And the equivalent for the previous entry, but how could I jump to the first entry with a single keyboard shortcut? Thank you!

**Comment by emmanueltouzery** [comment]
I found a way to achieve that..
```lua
      require('diffview').setup {
        keymaps = {
          view = {
            ["F"] = function() -- jump to first file in the diff
              local view = require'diffview.lib'.get_current_view()
              view:set_file(view.panel.files[1], false, true)
            end,
          },
```
works great!

**Comment by sindrets** [comment]
Cool that found a solution! But I think it would still be valuable to have actions for `select_[first|last]_entry`, so I'll keep the issue open.

**Comment by yungthai** [comment]
@sindrets I'll have a go adding this feature.
