### ISSUE TITLE
Viewing fugitive logs within Diffview

### ISSUE THREAD

**Issue by msvitok77** [sindrets/diffview.nvim#427]
Hi, is there a possibility to view vim fugitive logs from diffview? I know I can copy commit hash and :DiffviewOpen commithash<cr>, but maybe there is a better way similar to neogit integration:

```
integrations = {
        diffview = true,
    }
```

Thank you.

**Comment by sindrets** [comment]
What do you mean exactly by "fugitive logs"? Do you mean the git logs? Specifically the window you get when running fugitive's `:Git log` command? Describe in detail what you're trying to do.

**Comment by msvitok77** [comment]
Hi @sindrets . Sorry for being imprecise. Yes I meant git logs. So doing something like this:
1.) :G log<cr>
2.) find some commit I want to view diff for
3.) perform 'some' action to open Diffview (similar to neogit's `d` command)

**Comment by sindrets** [comment]
Currently we don't have any integration like this for Fugitive. I have actually implemented what you're describing [in my own config](https://github.com/sindrets/dotfiles/blob/master/.config/nvim/lua/user/plugins/fugitive.lua), but it's a bit hacky and I just never got around to fixing it up to include it in the plugin.

However, `:DiffviewFileHistory` is the git-log interface offered by this plugin. You should check it out, and see if it could replace your use of `:Git log`. At least when you intend to view diffs of the history, as this is what our interface excels at. We support a good number of the `git-log` command options, and if there's something you're missing: please feel free to open a feature request. Check `:h :DiffviewFileHistory` for more info.

**Comment by msvitok77** [comment]
aaa this is exactly what I need. I'm already using it for a specific file 🤦🏻‍♂️ :DiffviewFileHistory %<CR> ... I forgot to check that if no file is provided it works like git log. Thanks! BTW this plugin is really good.

**Comment by sindrets** [comment]
Great! Closing this issue as solved.
