### ISSUE TITLE
[Feature] Discard changes

### ISSUE THREAD

**Issue by kitallen23** [sindrets/diffview.nvim#43]
Hi! First, a big thanks for the plugin, I'm a big fan. As a colemak user, I'm very appreciative of the `disable_defaults` option.

However I occasionally find myself needing to discard an entire file. As far as I can see, this isn't a operation in your plugin.

Do you think this is a feature you would be willing to add at some point?

**Comment by sindrets** [comment]
Sure, that sounds useful. I'll implement it when I get some time.
