### ISSUE TITLE
[Bug] Missing Deleted files when show the changes

### ISSUE THREAD

**Issue by LintaoAmons** [sindrets/diffview.nvim#430]
### Description

Here's the content by `git show <commit-sha>`

![image](https://github.com/sindrets/diffview.nvim/assets/95092244/2c148900-3c5b-4847-8a87-90ead32df3fa)

But it didn't show in the `DiffviewOpen <commit-sha>`
![image](https://github.com/sindrets/diffview.nvim/assets/95092244/84fb7ee6-54ee-4167-8829-cf2f1ff06ec1)

### Expected behavior

Show the same changes even it's a deletion

### Actual behavior

The deleted files are missing

### Steps to reproduce

1. git commit with files deleted
2. `DiffviewOpen <commit-sha>`

### Health check

should be fine

### Log info

<details>
<summary>Relevant info from <code>:DiffviewLog</code></summary>

```
############################
### PUT LOG CONTENT HERE ###
############################
```

</details>

### Neovim version

```markdown
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Mac

**Comment by sindrets** [comment]
`:DiffviewOpen <REV>` gives you the diff between `<REV>` and the working tree. If the file was deleted in `<REV>`, and it's still deleted, then the diff between them is the empty set.

The equivalent of doing `git show <REV>` is `:DiffviewOpen <REV>^!`. This describes the *range* of a single commit.

For more info on Git's rev syntax, see "SPECIFYING REVISIONS" and "SPECIFYING RANGES" under `$ man git-rev-parse`.

**Comment by LintaoAmons** [comment]
Thx~ Now I understand more about git! 
But How do you think about the idea to add a Command `DiffviewShow <REF>`？
