### ISSUE TITLE
How Can I Expand All Fold by Default in DiffviewFileHistory?

### ISSUE THREAD

**Issue by imroc** [sindrets/diffview.nvim#437]
Everytime I use DIffviewFileHistory to see commit changes, I need to press `zR` to expand all fold to see the complete file content, Is there a way or option can expand all fold by default?

**Comment by gaslight217** [comment]
Same with @imroc, If there any way to unfold all code in diffview by default?

**Comment by gaslight217** [comment]
Find it, @imroc, https://github.com/sindrets/diffview.nvim/issues/236, try "foldenable = false"

**Comment by imroc** [comment]
@gaslight217 I use this config and it works for me:
```lua
      hooks = {
        diff_buf_win_enter = function()
          vim.opt_local.foldenable = false
        end,
      },

```
