### ISSUE TITLE
Merge Tool does not support diff3 conflictstyle

### ISSUE THREAD

**Issue by stimut** [sindrets/diffview.nvim#447]
If the `merge` config of git is set to use `conflictstyle = diff3` so that the original text is included under the `|||||||` marker when there is a conflict, then the Merge Tool doesn't recognize the conflict and puts the entire conflict section within the `LOCAL` changes.

**Comment by sindrets** [comment]
`diff3` conflict markers *are* supported.

> [...] the Merge Tool doesn't recognize the conflict and puts the entire conflict section within the LOCAL changes.

What exactly do you mean by this? That the conflict markers are still in the buffer? That's how it's supposed to work. The `LOCAL` buffer shows the file as it exists on your local file system. Which - during a merge - means that it will contain conflict markers.

The other windows in the view will show the different versions of the file that resulted in the conflict.

**Comment by stimut** [comment]
Oh I see. I didn't realise, sorry. It's not the way I'm used to 3-way merge tools working.

I'll close this as it's as-intended.
