### ISSUE TITLE
[Feature] Allow rearange diffview  index buffer position

### ISSUE THREAD

**Issue by SuperBo** [sindrets/diffview.nvim#448]
### Description

Right now the current window order is putting index as following

` the entries under "Changes" will have the index buffer on the left side, and the entries under "Staged changes" will have it on the right side)`

### Expected behavior

I came from lazygit experience, so I expect the with "Changes" files, the index should be in right and similar with "Staged", index should be in left.

Please allow one config option to let the user config the index buffer orientation.

### Actual behavior

Index is put on fixed position without any option to configure.

### Steps to reproduce

:DiffviewOpen

### Health check

<details>
<summary>Output of <code>:checkhealth diffview</code></summary>

```
#######################
### PUT OUTPUT HERE ###
#######################
```

</details>

### Log info

<details>
<summary>Relevant info from <code>:DiffviewLog</code></summary>

```
############################
### PUT LOG CONTENT HERE ###
############################
```

</details>

### Neovim version

```markdown
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891
```

### Operating system and version

macOS 14.0

**Comment by sindrets** [comment]
The windows are ordered chronologically (assuming left-to-right, top-to-bottom order). This means that you always get the older state first, followed by the newer state, which is intuitive.

What's the justification for arranging the layout in the inverse chronological order?

**Comment by SuperBo** [comment]
<img width="1774" alt="Screenshot 2023-12-17 at 11 28 04 PM" src="https://github.com/sindrets/diffview.nvim/assets/2666479/aa9af839-117c-4023-9b00-42231fb815fa">
Let take a look at this screenshot.

In the file panel, top-to-bottom direction, we apply a reverse chronological. This means we have newer file first (unstaged) then older (staged).

However in the file window buffer, we apply a reverse order (chronological order). This means we have older file first (index) on the left, and older file (working dir) on the right.

This inconsistent make me feel very strange at the first time I use Diffview.

**Comment by sindrets** [comment]
The sections in the file panel are not ordered by chronology. They're ordered by urgency ("what requires the users attention first?"):

1. Merge conflicts are always first: these require immediate attention.
2. Unstaged changes: this is always the changeset you're currently working on, and is where you're going to be determining what to include in a commit.
3. Staged changes: the changeset you've already marked to be included in the commit.

But this is unrelated to how the diff windows are arranged. Practically every tool that has a diff viewer displays diffs in chronological order, the same way we do in diffview.nvim. Off the top of my head I can think of:

- vim-fugitive
- GitHub
- GitLab
- BitBucket
- Delta
- VS Code
- All JetBrains IDEs
- Sublime Merge

If lazygit does something else here, they are clearly the outlier.

---

Anyway, you have now indirectly made the case for rearranging the sections in the file panel, which I'm willing to discuss. However, you haven't made an argument for why we should offer an option for arranging diff windows in reverse-chronological order.

**Comment by SuperBo** [comment]
I think you are correct, I have check other clients, all have the same arrangement with diffview.

My wrong impression really comes from this layout (unstaged changes are on the left, staged changes are in the right).
<img width="1474" alt="Screenshot 2023-12-18 at 7 59 45 AM" src="https://github.com/sindrets/diffview.nvim/assets/2666479/cb520206-d4f4-42cc-a542-f3f3133902d2">

Actually these are two **inline diff** windows, not the same as side-by-side diff window.

For file panel, I have just take a look at Gitlense, they put staged changes before unstaged changes.

<img width="286" alt="Screenshot 2023-12-18 at 8 09 15 AM" src="https://github.com/sindrets/diffview.nvim/assets/2666479/14ecec07-59db-4364-a595-e7455c8438c1">
<img width="286" alt="Screenshot 2023-12-18 at 8 11 30 AM" src="https://github.com/sindrets/diffview.nvim/assets/2666479/5b3b6b77-bab7-44a7-b03f-615a8bffac21">

**Comment by sindrets** [comment]
Closing as completed as at seems we came to an understanding with regards to the original issue.

If you think we should rearrange the sections in the file panel, please open a new issue with arguments for why think so, and we can discuss it further. Mind you, the arguments need to be more meaningful than "it's what VSCode does".
