### ISSUE TITLE
Questions on example image

### ISSUE THREAD

**Issue by HumblePresent** [sindrets/diffview.nvim#45]
Hi! This plugin looks great and I can't wait to try it out! The example image in the README looks very cool and I had a few questions about that setup.

1. Which plugin are you using to get both listchars and indent guides to show together? The indent guide plugin I'm using currently doesn't support this.
2. What colorscheme is being used? I really like the look.

Great work on this plugin. Along with Neogit this will be so helpful.

**Comment by sindrets** [comment]
Glad you like it!

1. The indent plugin is [indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim).
2. The colorscheme is [tokyonight](https://github.com/folke/tokyonight.nvim).
