### ISSUE TITLE
[Question] How to open a patch or diff text file by diffview

### ISSUE THREAD

**Issue by LintaoAmons** [sindrets/diffview.nvim#451]
So if I already have a `git diff text` file, how can I render it by diffview?

like I already have a this file open in a buffer, I want to open it by diffview to have a better view
![image](https://github.com/sindrets/diffview.nvim/assets/95092244/75156344-a0e4-4ca6-b5d6-a6adbc1e7122)

**Comment by sindrets** [comment]
I believe we are already tracking this issue in #288.
