### ISSUE TITLE
Custom diff map not honored

### ISSUE THREAD

**Issue by brucejxz** [sindrets/diffview.nvim#460]
Hey. So I have a the following mappings set up to centralise the diff hunk after jumping to it:

```
vim.keymap.set('n', '[c', '[czz', { desc = 'Jump to previous hunk' })
vim.keymap.set('n', ']c', ']czz', { desc = 'Jump to next hunk' })
```

These work when I run:

```
nvim -d file_1 file_2
```

But they don't work in a `:DiffviewOpen` view. Any idea why not?

**Comment by sindrets** [comment]
No, I don't know. And I won't try to guess why you're having this problem either, because you didn't fill out the bug template. But we don't currently change that mapping by default.
