### ISSUE TITLE
[Question] How to open entry of the file panel via lua/command?

### ISSUE THREAD

**Issue by Otterpatsch** [sindrets/diffview.nvim#464]
Hello there,
First of all i very much like your plugin. So much that im trying to use it within the plugin im trying to create (bitbucket.nvim basically just to review PRs of bitbuckets repos).

So i want to jump to a file of the file panel given its relative(or absolut if needed) file path 
![image](https://github.com/sindrets/diffview.nvim/assets/29692215/f588c3ca-780a-434f-9ee6-38f47d420ea6)

For example i would like to jump to the file to which a comment is connected
![image](https://github.com/sindrets/diffview.nvim/assets/29692215/2043463d-4ee1-4952-b01c-c2f81a39bc82)

I tried to dig into your code but as im just picked up lua like 4 days ago im struggle a bit.
[    select_entry = function()](https://github.com/sindrets/diffview.nvim/blob/3dc498c9777fe79156f3d32dddd483b8b3dbd95f/lua/diffview/scene/views/diff/listeners.lua#L80)
So how to i "fake" a item for the linked function?  Or is there maybe another function which does that?

**Comment by jakubbortlik** [comment]
Hi @Otterpatsch, not sure if this is still relevant, but you can take inspiration from how [gitlab.nvim](https://github.com/harrisoncramer/gitlab.nvim) does this: You can [focus the file panel](https://github.com/harrisoncramer/gitlab.nvim/blob/138b96baea02629ea007398d6d196c6f8d4a6c25/lua/gitlab/reviewer/init.lua#L104) and then use the `diffview.lib.get_current_view()` to get the current view and then you should be able to `view:set_file(file)`.

**Comment by sindrets** [comment]
You would be reaching into the internal API for this, which could change at any point. But I believe you could do this (untested):

```lua
local DiffView = require("diffview.scene.views.diff.DiffView").DiffView
local async = require("diffview.async")

async.void(function()
  local view = require("diffview.lib").get_current_view()

  if view and DiffView:ancestorof(view) then
    --- @cast view DiffView
    async.await(view:set_file_by_path("some/file/path"))
  end
end)()
```

The file path here would be relative to the repository top-level. That can be found from `view.adapter.ctx.toplevel`.
