### ISSUE TITLE
No syntax highlighting for changed / deleted / updated lines

### ISSUE THREAD

**Issue by t-ober** [sindrets/diffview.nvim#467]
I can not quit figure out why there is no syntax highlighting going on for changed / deleted / updated lines. That makes the corresponding code quite hard to read. 

Here is an example: 

![image](https://github.com/sindrets/diffview.nvim/assets/63147366/f3d42dc9-306b-4987-b205-f5effbcecf50)

It does not seem to be dependent on the theme I am using.
Any pointers would be much appreciated 🙂

**Comment by t-ober** [comment]
I am using [NvChad](https://github.com/NvChad/NvChad/), so that might have something to do with how they set up the ui and themes.

**Comment by eonpatapon** [comment]
Check the highlight you have for `DiffText`

**Comment by sindrets** [comment]
We don't change any builtin highlights here. This is related to your color scheme. If you wish to customize the diff highlights, the relevant groups are documented under `:h hl-DiffAdd`.
