### ISSUE TITLE
Triple-dot commit range results in double-dot commit range

### ISSUE THREAD

**Issue by Gelio** [sindrets/diffview.nvim#47]
Hey :slightly_smiling_face: 

I've tried to run `:DiffviewOpen origin/master...` but it seems to show the diff for `origin/master..HEAD` (double-dot range). How do I get the plugin to show the diff for a triple-dot range?

**Comment by sindrets** [comment]
The short answer is: you can't at the moment.

I'm using `git rev-parse` to parse revs, but `git diff` normally treats symmetrical difference notation (triple dot) different from most other git operations. I think I'll have to make an exception for symmetrical difference notation. It shouldn't be too hard, I'll see if I can get it done soon.

**Comment by Gelio** [comment]
Seems to work like a charm, thanks!
