### ISSUE TITLE
[Feature] An option to show the directory structure

### ISSUE THREAD

**Issue by GregoRCodi** [sindrets/diffview.nvim#48]
I would love to see the directory structure in the files panel. That will give me immediate clarity how the files relate to each other (are they in the same directory?).

I would imagine there could be a mapping that would change the files view to either a directory view (hierarchical) or a flat list (as it is now).

Being able to collapse/open directories would be an additional benefit

**Comment by sindrets** [comment]
I'm really not a fan of this idea. I think it would introduce unnecessary visual complexity. I want the file panel to give users an immediate idea of exactly what files have been changed, and I think a file tree would only be visual noise in this interface. Besides, file tree plugins exist in plentiful numbers. I think the job of giving you a mental model of the file structure are better left to such plugins.

The file panel already lists files sorted by path (so files in the same directory will be grouped together), and the full path is displayed next to the basename. If the paths are too long to read, you can temporarily resize the window, or even move it to the bottom of the screen.

Maybe I'll reconsider this at some point, but for now I'm closing this.

**Comment by GregoRCodi** [comment]
I understand, thanks for the response
