### ISSUE TITLE
[Feature request] git rebase --continue workflow

### ISSUE THREAD

**Issue by lobneroO** [sindrets/diffview.nvim#505]
### Description

It would be nice to have an integrated workflow for stage+commit+`git rebase --continue`
I just went through a rebase with closing, continuing and reopening diffview three times, and while I probably didn't do it optimally, I didn't see a way to handle it all from within diffview. The staging is part of diffview (and committing as well, I think?), but the rebase continue is not so far as I can tell.

### Actual behavior

Have a shortcut that lets you easily do `git rebase --continue` without leaving diffview

### Steps to reproduce

1. Start a rebase which will have to be continued at least once
2. Open nvim with diffview
3. Merge changes for the first rebase step
4. Stage and commit
5. Do an extra `git rebase --continue` outside of diffview
6. Go back into diffview

### Health check

Not needed for feature request

### Log info

<details>
<summary>Relevant info from <code>:DiffviewLog</code></summary>

```
############################
### PUT LOG CONTENT HERE ###
############################
```

</details>

### Neovim version

```markdown
NVIM v0.10.0
```

### Operating system and version

All of them

**Comment by lobneroO** [comment]
Sorry about the bug label. I couldn't see a way create this as a feature request for some reason

**Comment by sindrets** [comment]
> The staging is part of diffview (and committing as well, I think?)

[Committing is intentionally not, no.](https://github.com/sindrets/diffview.nvim/blob/main/USAGE.md#committing)

The following section in that document should also tell you how you can set up some mappings to call `git rebase --continue` in whatever fashion best suites your config.

**Comment by sindrets** [comment]
Example from my own config: https://github.com/sindrets/dotfiles/blob/40e20f7f68cf55f175d94a92b31a64d66ed3c059/.config/nvim/lua/user/plugins/diffview.lua#L107
