### ISSUE TITLE
Hooks for tweaking diff highlights

### ISSUE THREAD

**Issue by YorickPeterse** [sindrets/diffview.nvim#52]
I realise this is a bit of an odd request, but here goes anyway:

Highlighting of diffs in (Neo)Vim is a counter-intuitive. When you have version A and B of a file and diff them, A will show the diff relative to B, while B shows the diff relative to A. In practise this means that e.g. a line removed by B shows up as an addition in A, while not showing up in B. Here's an example of that:

![Screenshot from 2021-08-02 18-02-24](https://user-images.githubusercontent.com/86065/127890650-4067fa8a-a21f-4b66-b32f-244198f834db.png)

In addition, changes in B tend to highlighted using the `DiffText` highlight group. This can result in diffs largely looking similar highlight wise, making it difficult to see what actually changed.

For vim-fugitive I have a hack to fix this (see [here](https://www.reddit.com/r/neovim/comments/ok8u3w/improving_diff_highlighting_when_using_fugitive/)). This basically uses `winhl` to overwrite highlight groups in the appropriate fugitive buffer. The result is something that looks like this:

![Screenshot from 2021-08-02 18-05-06](https://user-images.githubusercontent.com/86065/127891023-26d2c97c-1b13-49b1-a302-e102b55726c8.png)

Note how in the old version (left) deletions are shown in red, while additions in the new file (right) are in green. This is what you'd expect when looking at a diff, instead of the default Vim mess.

For diffview.nvim this doesn't work. Buffer names don't have predictable names I can use to inject my `winhl` rules. There are no hooks of any kind that I can tap into either. Which brings me to my request:

Would it be possible to somehow expose a hook that runs for old/new versions in a diff, or perhaps use specific buffer names (e.g. `before: diffview/XXX.rb`) for old/new versions? That would make it possible to fix the diff highlights.

**Comment by YorickPeterse** [comment]
To further illustrate why this would be useful: in the left panel of the first screenshot, the "This class ..." paragraph is shown as an addition (DiffAdd). That's plain wrong, because the line isn't added in the branch I compared the right side with (it was added _much_ earlier). Vim however shows it as `DiffAdd` because the line is removed in the right panel.

I'm not aware of there being a better way of fixing this, short of injecting `winhl` rules into the proper buffer. Seeing how vimdiff has behaved this way since basically forever, I doubt it will change any time soon either.

**Comment by sindrets** [comment]
This is interesting. It would be nice to implement this in some way as an optional feature. I'll have to think about the best way to do this. In the meantime, I did manage to get your desired effect to work in diffview by adding this to my config:

```lua
local M = {}

function M.apply_diff_tweaks()
  vim.schedule(function ()
    local view = require'diffview.lib'.get_current_diffview()
    if view then
      local curhl = vim.wo[view.left_winid].winhl
      vim.wo[view.left_winid].winhl = table.concat({
          "DiffAdd:DiffAddAsDelete",
          curhl ~= "" and curhl or nil
        }, ",")
    end
  end)
end

vim.api.nvim_exec([[
  hi! def DiffAddAsDelete guibg=#3C2C3C

  augroup diffview_config
    au!
    au TabNew * lua DiffviewConfig.apply_diff_tweaks()
  augroup END
]], false)

_G.DiffviewConfig = M
```

**Comment by YorickPeterse** [comment]
@sindrets Ah, I wasn't aware of the `get_current_diffview` function. I'll see if I can adopt this somehow.

As an aside: I thinm the `vim.schedule` call here isn't necessary, but I could be mistaken.

**Comment by sindrets** [comment]
> As an aside: I think the vim.schedule call here isn't necessary, but I could be mistaken.

No it is necessary, because I'm triggering the function on `TabNew`, which is before diffview has been able to initialize the layout. Before the `schedule` the diff windows don't exist yet.
