### ISSUE TITLE
"Zoom out" workflow to show all diffs in a particular commit

### ISSUE THREAD

**Issue by brucejxz** [sindrets/diffview.nvim#538]
Firstly, sorry if this is the wrong place for this but I couldn't find any other discussion forum to post it. 

So I have a keymap for `:DiffviewFileHistory %` as I almost always want to quickly browse the changes made to just the current file without cycling through other files that are present in the commits. However, once I've found the commit that I'm interested in, I would then like to be able "zoom out" and now see the diffs for all files in that commit. Is it possible to do this somehow? I see that I can press `L` on the commit to show the description and which files were changed but I would like to have the awesome diffview for all files in the commit.

**Comment by maggflor** [comment]
I think there is a default keymap for that.

When I'm hovering over a commit, I can do `Ctrl-Alt-d` to open the full commit in a new diffview tab.
Try pressing `g?` to see, whether this keymap is available for you, I'm not sure if it's default or added by lazyvim.

**Comment by brucejxz** [comment]
How did I not see this? Thank you so much @maggflor - this is absolutely glorious.
