### ISSUE TITLE
Better command completion: branches / tags / files in the completion menu

### ISSUE THREAD

**Issue by ghillb** [sindrets/diffview.nvim#54]
What I'm missing from this incredibly useful plugin is a nice completion for the `:DiffviewOpen` command. When I toggle the completion with vim fugitive's `:Gvdiffsplit` for example, I get a list of all tags, branches and files. `:DiffviewOpen` only provides a list of hashes, which I find hard to utilize and files after closing arguments with `--`. 

A comparison between the two:
![gvdiffvsdiffview](https://user-images.githubusercontent.com/35503959/129258825-b16852bd-04c0-4aa6-9c5a-a563cdd7289a.png)

Any chance we can get something like this for diffview.nvim?

**Comment by sindrets** [comment]
Yes, I agree. The completion isn't great right now and I'm planning to improve it. I realize the list of commit hashes isn't very useful, and I did it kind of just as a temporary thing.
