### ISSUE TITLE
Question: Sidebar tabline title

### ISSUE THREAD

**Issue by romgrk** [sindrets/diffview.nvim#55]
Hey, in the screenshot the tabline shows "Source Control", how can I enable that? Is there an autocmd/callback that is fired when the view is openeds/closed?

Edit: and while I'm here, how do you get the removed hunks to show like this?
![Screenshot from 2021-08-15 23-09-26](https://user-images.githubusercontent.com/1423607/129506466-f3ffad13-a45f-4b05-8f9b-86b8dea6a1bf.png)

**Comment by sindrets** [comment]
The "Source Control" title in the tabline is [a feature from `nvim-bufferline`](https://github.com/akinsho/nvim-bufferline.lua#sidebar-offset-1) that allows you to configure titles, offsets or decorations above vertical splits. There are currently no autocmds fired when opening / closing a diffview.

For your second question, see my response here: #35.

**Comment by sindrets** [comment]
Closing due to no follow-up from OP. And the questions have been answered. Let me know if anything is still unclear.
