### ISSUE TITLE
Files without icons are aligned differently 

### ISSUE THREAD

**Issue by romgrk** [sindrets/diffview.nvim#56]
When a file doesn't have an icon, it's aligned differently from the rest. It would be nice to keep the same alignment, either by having a default icon or by adding spaces.

![Screenshot from 2021-08-15 23-13-58](https://user-images.githubusercontent.com/1423607/129506773-b04ffd5e-116e-4e29-8c57-bf7072264f8d.png)

**Comment by sindrets** [comment]
That's reasonable. I'm currently working on some big refactoring, so I'll fix this after I've merged that.

**Comment by sindrets** [comment]
Fixed via 15ab6ab2fe88844238db1a175d18595fc2553c41.
