### ISSUE TITLE
Feature request: commit from diffview interface

### ISSUE THREAD

**Issue by romgrk** [sindrets/diffview.nvim#57]
It would be nice if it was possible to commit from the diffview interface, as can be done through the fugitive interface.

**Comment by sindrets** [comment]
This is something I won't do for the same [reasons I've previously explained about design specificity](https://github.com/sindrets/diffview.nvim/issues/31#issuecomment-855380352). 

To summarize: this already exists, and it's been done well in other plugins. By reinventing a feature like this when I have nothing to add, I would just be contributing to feature redundancy in the plugin ecosystem. Like you mentioned, Fugitive already offers this, Neogit does as well, and they both work with or without diffview.nvim.

I want diffview to be focused on just being a good git diff viewer. You can now also stage files from diffview, as I felt it was a natural addition to the workflow in the file panel. But a commit feature wouldn't do anything that `:Git commit` in Fugitive doesn't already do.

**Comment by LintaoAmons** [comment]
Like, I already fill every goal that I required with the Dffview except the final commit command. 

But for only the commit action, I need to install one other plugin, which may be bundled with a lot of other features I won't touch.

By the way, this feeling may cause by the IDEA. I use IDEA to do the java development, and I'm more than happy to find a plugin that is as easy to use and as good diff view as IDEA did. But missing the last part of commit.

- IDEA diff view
![image](https://user-images.githubusercontent.com/95092244/170871566-0557b1bf-b65b-4e86-a905-be5e7c2862ed.png)

**Comment by sindrets** [comment]
@LintaoAmons You don't need to install anything to do a git commit. There are a number of options for accomplishing this with out-of-the-box nvim:

### Use `:!`

If you just need to write a simple commit title this is probably the simplest solution:

`:!git commit -m 'some commit message'`

### Use `<C-z>`

Assuming you're using terminal nvim: you are already in a terminal. Just press `<C-z>` to suspend the current process. Perform a normal `git commit` in the shell. And finally just run `fg` to bring nvim back to the foreground.

### Use `:term [cmd]`

This is nvim's provided way to run interactive shell commands. Just run `:term git commit`, and it will open your configured git editor. Do note however that if your configured editor is nvim, it will open a nested nvim instance. This can be easily avoided by installing the [neovim-remote](https://github.com/mhinz/neovim-remote), and [adjusting your env variables accordingly](https://github.com/sindrets/dotfiles/blob/07bd1b4d7674103186bafa686bc970e076c0bca0/.config/nvim/lua/nvim-config/settings.lua#L118-L122). Neovim-remote is a client that can interact with nvim's builtin server. In the future this probably won't be needed, as work is being done to bring it's functionality into core. And some parts exist in core already (see `:h --remote`).

I still really recommend getting fugitive, as it's a remarkably good git plugin, and it integrates with (n)vim in a very natural way. It has a very little opinionated design, meaning that if you're familiar with git, you're familiar with fugitive. And I believe that when one is using git as their VCS, one is going to need to interact with it more than just diffing and staging at one point or another.

I hope this helps!

**Comment by LintaoAmons** [comment]
Thx~ I will try fugitive after your recommendations~ 

LOL, Buy the way, currently I use Diffview to review the code changes I made. Then use Toggleterm to pop up a lazygit window to do the commit. Something use tmux to open a new pane to do the commit thing. I prefer TUI better than `:!`~
