### ISSUE TITLE
Nor working when neovim is opened not in git root

### ISSUE THREAD

**Issue by dragonofdeath** [sindrets/diffview.nvim#6]
Hi, great plugin! Wanted to have something like this for some time now.

One issue though - if neovim is started in subdirectory of repository the `:DiffviewOpen` right window is empty - the current file state is not displayed. It looks that there is some issue with file resolution as file path is resolved to git root, but as the vim is started it subdirectory it can not find the right file.

**Comment by sindrets** [comment]
Indeed, we should use absolute paths for opening local files. I'll fix this right away.
