### ISSUE TITLE
Is the documentation up-to-date?

### ISSUE THREAD

**Issue by farzadmf** [sindrets/diffview.nvim#72]
Hi, I installed this plugin, mainly because of `DiffviewFileHistory`, however that doesn't seem to be a command I can run, despite being mentioned in the documentation (`README` basically)

Thank you

**Comment by sindrets** [comment]
Yes, both the documentation and the README are up-to-date, and that command should be available. I suspect you have either not installed the plugin properly, or your Neovim version is <0.5. The plugin won't load unless your Neovim version is compatible.

**Comment by farzadmf** [comment]
> not installed the plugin properly

I've added the `Plug 'sindrets/diffview.nvim'` to my config, not sure if there's anything else I need to do :thinking: 

(didn't add any config for now because I thought the availability of the command won't be affected by the config)

> Neovim version is <0.5

That's not the case; my version: `NVIM v0.6.0-dev+43-g02bf251bb`

> The plugin won't load unless your Neovim version is compatible

I think the plugin is loaded because I see these commands:
![diffview](https://user-images.githubusercontent.com/5768792/132697786-a8162bfb-a7d4-4f9d-9818-f57081704b17.png)

I seem to miss the `DiffviewFileHistory` command there

**Comment by sindrets** [comment]
Hm, that is very strange. The only thing I can think is that somehow you have an outdated version? Have you run `:PlugUpdate`? 

If you navigate to where diffview is installed, what is the output of:

```sh
git log -n1 --oneline
```

**Comment by farzadmf** [comment]
OMG, I'm so sorry @sindrets , I hadn't realized I had included this plugin before and I just did `:PlugInstall`. `:PlugUpdate` did the trick.

Sorry again for the confusion,

And thank you for the great plugin. I had installed it before, but hadn't used it, gonna use it more :slightly_smiling_face:

**Comment by sindrets** [comment]
No worries, glad you figured it out :)
