### ISSUE TITLE
Error executing lua ...

### ISSUE THREAD

**Issue by carand** [sindrets/diffview.nvim#74]
Hello everyone,

I have some problems to run your plugin.
 
`E5108: Error executing lua .../plugged/diffview.nvim/lua/diffview/views/file_entry.lua:154: attempt to index field 'opt' (a nil value)    `

Can anyone help me?

`NVIM v0.5.0-dev+1295-g3fc71ea22
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az64-704
`

Thanks for help.

**Comment by sindrets** [comment]
Looks like your Neovim is outdated. You're still running an old dev build of 0.5. Please update to the release version.

**Comment by carand** [comment]
@sindrets 
 
Thanks for help, it works with version 0.6.0
