### ISSUE TITLE
Callback for ftplugin style setup when opening diffview.nvim

### ISSUE THREAD

**Issue by IndianBoy42** [sindrets/diffview.nvim#75]
I want to add some `<buffer>` keymaps that are only active in the diffview. I know that we can bind any maps in `setup.key_bindings`, but I also want to add which-key.nvim entries for description. I think a more flexible method is to be able to register a callback that is run when opening a new diffview buffer (like ftplugin)

**Comment by p00f** [comment]
Yes, for example I want to `set nowrap` in the diff buffers

**Comment by sindrets** [comment]
@IndianBoy42 Does #99 solve this for you?

**Comment by sindrets** [comment]
This should be resolved now as I've implemented both autocommands as well as a lua API for hooking into events emitted from Diffview. But just let me know if there are any problems.
