### ISSUE TITLE
DiffViewFileHistory doesn't work if .git is on upper level

### ISSUE THREAD

**Issue by timsofteng** [sindrets/diffview.nvim#76]
Hello.
DiffViewFileHistory doent work if my working directory is not on same level with .git.
Sometimes I open my project deeper than root level.
Can it be fixed?

**Comment by timsofteng** [comment]
Hello. Unfortunately the issue still exists

**Comment by sindrets** [comment]
Yes, I was aware. But there was a PR in the works, so I was waiting to see where that was going.

Regardless: fixed via 7aa94bcb4eefb07d49a94e1622f845b16f59833f.
