### ISSUE TITLE
How to map DiffviewClose to gq

### ISSUE THREAD

**Issue by timsofteng** [sindrets/diffview.nvim#78]
Hello.
How can i map `DiffvewClose` to `gq` only in Diffvew active tab?

**Comment by sindrets** [comment]
Try:
```lua
{
  key_bindings = {
    view = {
      -- other mappings ...
      ["gq"] = "<CMD>DiffviewClose<CR>",
    },
    file_panel = {
      -- optionally add it to the file panel as well:
      ["gq"] = "<CMD>DiffviewClose<CR>",
    }
  }
}
```

**Comment by timsofteng** [comment]
> Try:
> 
> ```lua
> {
>   key_bindings = {
>     view = {
>       -- other mappings ...
>       ["gq"] = "<CMD>DiffviewClose<CR>",
>     },
>     file_panel = {
>       -- optionally add it to the file panel as well:
>       ["gq"] = "<CMD>DiffviewClose<CR>",
>     }
>   }
> }
> ```

It works!
Thanks!
It would be helpfull to add it to readme.

I close the issue.
