### ISSUE TITLE
 [feature] Standard vimdiff commands and git add on save

### ISSUE THREAD

**Issue by kunzaatko** [sindrets/diffview.nvim#8]
Hey! Thank you for making this plugin!
I think the interaction with the diffs should function on the repo (sorry, but I do not know how to word this). It should work as a standard vimdiff view.

The example of usage that would be nice:
- If I am in the _Index_ diff, then `:diffput` and `:diffget` should work on the hunk as in a vimdiff. Now this returns an error as the diff is not marked as __modifiable__
- If I save the "_Head_" diff (the one on the left) this should stage the the changes added so that I can now commit

Here is a cast of the error now and how I would expect it to work (demostrated on `:Gvdiffsplit` from fugitive)
[![asciicast](https://asciinema.org/a/m5jWazRyLfysGFVrtK9tlcfhU.svg)](https://asciinema.org/a/m5jWazRyLfysGFVrtK9tlcfhU)§

**Comment by sindrets** [comment]
Thank you for the request, but I don't want Diffview to handle staging. There are a number of great plugins that already handle all forms of hunk staging (and all other forms of staging). Both [gitgutter](https://github.com/airblade/vim-gitgutter) and [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim) let you stage hunks directly from the editor. And for that reason I don't want buffers that represent files from git history to be modifiable.

On the topic of `diffget` and `diffput`, these commands work if the target buffer is a local file. So when comparing against some commit, you can use `diffput` from the left window, and `diffget` from the right window.

One way you might handle the example scenario you described in the recording using gitsigns.nvim as an example:
Move the cursor over the hunk you want to stage, call `:Gitsigns stage_hunk`. That's it. When you refresh the Diffview, the staging will be reflected.

If you really like the Fugitive way of staging hunks, there is nothing wrong about keeping Fugitve around, I still use Fugitive myself.

**Comment by kunzaatko** [comment]
I agree that there are already other methods to do this and therefore would be an unnecessary to have to implement it and maintain it. I will look into the `Gitsigns` method that you recommended. It seems that except the range staging, It will be exactly what I was after. Thanks!
