### ISSUE TITLE
cb("close") keybinding doesn't work in `:DiffviewOpen`

### ISSUE THREAD

**Issue by p00f** [sindrets/diffview.nvim#96]
My setup:
```lua
  local cb = (require("diffview.config")).diffview_callback
  require("diffview")).setup({
    enhanced_diff_hl = true,
    key_bindings = {
      file_history_panel = { q = cb("close") },
      file_panel = { q = cb("close") },
      view = { q = cb("close") },
    },
  }
```

However, when i press q in the diff buffer nothing happens. Note that it doesn't start recording macros when I press another letter after q, so atleast it is taking over keybindings

The mapping works in `:DiffviewFileHistory`

**Comment by gegoune** [comment]
@p00f I use maps to commands such as:
```lua
key_bindings = {                                        
  file_history_panel = { q = '<Cmd>DiffviewClose<CR>' },
  file_panel = { q = '<Cmd>DiffviewClose<CR>' },        
  view = { q = '<Cmd>DiffviewClose<CR>' },              
},                                                      
```
and they work just fine. Not sure why callback wouldn't.

**Comment by p00f** [comment]
that works for me too, thanks

**Comment by sindrets** [comment]
Diff views aren't subscribed to the `close` event. This is an oversight. I added the close event when I added file history, and I forgot to also have diff views subscribed to the event. I'll fix this soon.

**Comment by smackesey** [comment]
A little confused-- `cb('close')` does not work as I would expect in the file panel, it just causes the file panel itself to be closed, rather than doing the equivalent of `DiffviewClose`. Is this expected?

**Comment by sindrets** [comment]
@smackesey Yes, it's intended. The `close` event is contextual. It will always target whatever context you are in. So when invoked from a panel (file panel, option panel), it will close the panel. When invoked from one of the diff buffers it targets the entire view (because the diff buffers are never meant to be individually closed. Thus events invoked from the diff buffers will target the entire view.).

If you want a mapping that always closes the entire view use `<Cmd>DiffviewClose<CR>`.

**Comment by smackesey** [comment]
Thanks for clarifying and for this nice plugin.

FWIW, I think you should add a "cb" event that executes a DiffviewClose. It's a bit awkward that all the documented mappings use `cb`, but this one bit of common functionality requires a different format. Also, it's not very clear from the docs that you even _can_ pass anything other than a `cb` to the view tables, it took me a while to figure out how to set up a mapping for `DiffviewClose`.

**Comment by sindrets** [comment]
@smackesey I agree that keymaps should be documented better. But also - for clarity - there's nothing special happening here behind the scenes, and this is a somewhat common pattern for doing plugin mappings in lua plugin configs. The keys in the table are the `lhs` and the values are the `rhs` of a `:h nvim_set_keymap()` call. The `cb()` function is just a convenience utility that produces a string like:

```lua
cb("close")
-> "<Cmd>lua require'diffview'.trigger_event('close')<CR>"
```

So the value you provide as the `rhs` can be anything you would use in a mapping. Regardless, I'll improve the documentation when I find the time.
