### ISSUE TITLE
scrollopt gets reset after `:DiffviewOpen`

### ISSUE THREAD

**Issue by p00f** [sindrets/diffview.nvim#97]
I have scrollopt set to ver,hor,jump but after opening diffview it gets reset to ver,jump

(I want to use horizontal scrollbind with nowrap)

**Comment by sindrets** [comment]
I never adjust `scrollopt` anywhere in the code, so I don't know what this is about, but I'll have a closer look soon.

**Comment by sindrets** [comment]
The culprit was `:diffoff` which resets this option. Should be fixed now.

**Comment by p00f** [comment]
Thanks!
