### ISSUE TITLE
Auto open files

### ISSUE THREAD

**Issue by ziulev** [sindrets/diffview.nvim#98]
Hey 👋
Is there any way to enable automatic opening files (or commits in the history)

For example:
I have two files with changes. I use `j` `k` to select them in the tree. I would like them to open automatically without when I select one of them? I mean without `o` or `enter` etc.

**Comment by sindrets** [comment]
Yes. Just change the mappings for j and k to map to the `select_next_entry` and `select_prev_entry` callbacks instead. I'll note that `<tab>` and `<s-tab>` already have these mappings by default.
